### ISSUE TITLE
Correct release ci hash output

### ISSUE THREAD

**Issue by fewensa** [darwinia-network/darwinia#1004]
1.
The call index for authorize_upgrade is 2, but subwasm default is 0x03
https://github.com/chevdor/subwasm#command-info

```
#[pallet::call_index(2)]
#[pallet::weight((1_000_000, DispatchClass::Operational))]
pub fn authorize_upgrade(origin: OriginFor<T>, code_hash: T::Hash) -> DispatchResult {
ensure_root(origin)?;

  AuthorizedUpgrade::<T>::put(&code_hash);

  Self::deposit_event(Event::UpgradeAuthorized { code_hash }); 
  Ok(())
}
```

should set environment `AUTHORIZE_UPGRADE_PREFIX=2` 

2.
add blake2_256 hash to release template

**Comment by AurevoirXavier** [comment]
How's the progress?

**Comment by fewensa** [comment]
Today will be done for this.

**Comment by fewensa** [comment]
https://github.com/fewensa/darwinia/actions

I'm test in my forked repository
