### ISSUE TITLE
eth_getLogs performance issue

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia#1015]
> when our server boots, it fetches all events starting from the block the contract was deployed. i'm trying to look up events in batches of 500 blocks for the last ~10days, which works initially, but eventually i seem to get rate limited/banned before i can grab them all, and the rpc only returns 502 Bad Gateway from there on for each request.
> this would also mean the game isn't available for 10min or so after each app deployment or server restart, whereas other networks are fully initialized in 20-60sec tops, despite running for months already with a whole lot more blocks to look up. going forward, this is becoming an even bigger scaling problem, as the number of blocks to look up is growing steadily.

**Comment by flipchan** [comment]
has this been resolved?

**Comment by boundless-forest** [comment]
> has this been resolved?

Let's see if this is solved after https://github.com/paritytech/frontier/pull/883 included later.

**Comment by hujw77** [comment]
```sh
curl -fsS https://pangolin-rpc.darwinia.network -d '{"id":1,"jsonrpc":"2.0","method":"eth_newFilter","params":[{"address":"0x7F2573872aDeE56Ab8D80A32Df66c26FfcEB070B","fromBlock":"346190","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]}]}' -H 'Content-Type: application/json'
time curl -fsS https://pangolin-rpc.darwinia.network -d '{"id":1,"jsonrpc":"2.0","method":"eth_getFilterLogs","params":["4"]}' -H 'Content-Type: application/json'

________________________________________________________
Executed in    2.04 secs      fish           external
   usr time   20.63 millis    0.28 millis   20.35 millis
   sys time   16.22 millis    1.60 millis   14.62 millis

```

**Comment by hujw77** [comment]
```sh
time curl -fsS http://g1.testnets.darwinia.network:9940 -d '{"id":1,"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock":"346190","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]}]}' -H 'Content-Type: application/json'
{"jsonrpc":"2.0","error":{"code":-32603,"message":"query timeout of 10 seconds exceeded"},"id":1}
________________________________________________________
Executed in   10.78 secs      fish           external
   usr time    7.46 millis    0.32 millis    7.14 millis
   sys time   14.54 millis    1.71 millis   12.84 millis
```
