### ISSUE TITLE
Missing `OufOfGas` error message 

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia#1053]
https://github.com/darwinia-network/darwinia/blob/71ff02df997ef60a04ba655c1da18b6531be09bf/precompile/bls12-381/src/lib.rs#LL61C5-L61C5

**Comment by boundless-forest** [comment]
Please increase the gas limit for this transaction as the current input limit is insufficient, resulting in an OutOfGas error.

```rs
#[inline]
/// Record an explicit cost.
pub fn record_cost(&mut self, cost: u64) -> Result<(), ExitError> {
	event!(RecordCost { cost, snapshot: self.snapshot() });

	let all_gas_cost = self.total_used_gas() + cost;
	if self.gas_limit < all_gas_cost {
		self.inner = Err(ExitError::OutOfGas);
		return Err(ExitError::OutOfGas);
	}

	self.inner_mut()?.used_gas += cost;
	Ok(())
}

```

**Comment by boundless-forest** [comment]
There is a test case I wrote today that error can be successfully return the error.  I close it now, feel free to reopen it if you still have questions.

https://github.com/darwinia-network/darwinia/pull/1079/files#diff-781567cdafa8636f475dbdf76f00c7b135683a698eb653e38c36416e6d527d92
