### ISSUE TITLE
Dispatch precompile v2

### ISSUE THREAD

**Issue by boundless-forest** [darwinia-network/darwinia#1097]
Currently, the darwinia runtime uses the frontier's dispatch precompile to connect the ethereum smart contract model with the substrate runtime's call execution model.  But there are some issues we found in the usage process:

1. No selector for this precompile, it's awkward in some cases that require you to enter the method selector in some ethereum tool.
2. Should we add a filter to restrict only allowed calls can be dispatched via this way?

**Comment by hackfisher** [comment]
Why dispatch precompile require call's dispatch info class to be `DispatchClass::Normal`, root will need to call some `DispatchClass::Operational` calls


https://github.com/paritytech/frontier/blob/2b09a676cac8cca665c882a28bd13b2acef39395/frame/evm/precompile/dispatch/src/lib.rs#L67

**Comment by hackfisher** [comment]
> Why dispatch precompile require call's dispatch info class to be `DispatchClass::Normal`, root will need to call some `DispatchClass::Operational` calls
> 
> 
> 
> 
> 
> https://github.com/paritytech/frontier/blob/2b09a676cac8cca665c882a28bd13b2acef39395/frame/evm/precompile/dispatch/src/lib.rs#L67

Fix this by introduce a new util with_class call instead to override the dispatch class.(similar to with_weight which overrides weight)

**Comment by boundless-forest** [comment]
Waiting for https://github.com/paritytech/frontier/pull/1042 and https://github.com/paritytech/frontier/pull/1047
