### ISSUE TITLE
Add a new utility with_class call for root to override the dispatch info's class

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia#1099]
https://github.com/paritytech/substrate/blob/a6cb6d0fb79c303c9af513e856abfb61fc6d8d74/frame/utility/src/lib.rs#L475-L492

The main use case is for root contract to overpass the check of dispatch precompile, refer https://github.com/darwinia-network/darwinia/issues/1097#issuecomment-1506683902

**Comment by AurevoirXavier** [comment]
https://github.com/paritytech/substrate/pull/13912
