### ISSUE TITLE
Update `AddressMapping`

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#1101]
https://github.com/darwinia-network/darwinia/blob/9ba546de884b904ff95e127a1c7bef04619b2779/runtime/darwinia/src/pallets/evm.rs#L31-L32

**Comment by boundless-forest** [comment]
Duplicate with https://github.com/darwinia-network/darwinia/issues/1063

**Comment by AurevoirXavier** [comment]
Not really, but can be done at the same time.
