### ISSUE TITLE
Disable Vesting calls, and remove this pallet after all current vesting accounts ends.

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia#1123]

**Comment by AurevoirXavier** [comment]
Remove vesting for testnets first.

**Comment by AurevoirXavier** [comment]
Can we move the vesting to EVM contract?

**Comment by hackfisher** [comment]
> Can we move the vesting to EVM contract?

Yes, users/apps can deploy vesting smart contracts if they desire
