### ISSUE TITLE
the new_session function returns the next validators?

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/darwinia#1137]
the substrate code here https://github.com/paritytech/substrate/blob/master/frame/session/src/lib.rs#L656 getting the validators are used  by the next session.
But we use the power score to sort and insert the validators into storage [Exposure](https://github.com/darwinia-network/darwinia/blob/main/pallet/staking/src/lib.rs#L906), and use it in this session.
So if the validators are updated, then the set from Exposure and validators is different.

**Comment by AurevoirXavier** [comment]
`new_session` is implemented on our side.

https://github.com/darwinia-network/darwinia/blob/646ebca9e99c727febbf410007f0967610e5d39c/pallet/staking/src/lib.rs#L1003-L1011

**Comment by xiaoch05** [comment]
As I understand, this `new_session` is implemented in our code and then called by the substrate pallet. The argument passed in is the next session_index, so the collators set returned is used in the next session, which is the same as the Exposure set we inserted this time, but this Exposure set is only used in the current session and is emptied at the end of the current session. Right?

**Comment by AurevoirXavier** [comment]
Yep, I think there should be a snapshot for the exposures.

```
end session
	payout based on exposure

new session
	elect
	store exposures, keys
```
