### ISSUE TITLE
Use `transfer` instead of `set_lock` in feemarket?

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#1198]
The design pattern for the deposit/staking has been updated to this.

**Comment by boundless-forest** [comment]
Do you remember why the staking and deposit modules are designed the way they are? I would like to know the pros and cons of the two approaches. My understanding is that the transfer way is much more direct(simple), easy-understanding than the native lock, and suit for case that there are plent of lock and unlock operations. And the native balance lock is out of the box, easy to use. But I am not sure if there are any other advantages.
