### ISSUE TITLE
Do we need `pallet-assets` APIs?

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#1200]

**Comment by boundless-forest** [comment]
Which APIs do you mean?

**Comment by AurevoirXavier** [comment]
https://github.com/paritytech/cumulus/blob/211eead5cc3772afac9ab5e55df6df509ce9fcd6/parachains/runtimes/assets/common/src/runtime_api.rs#L32-L46

**Comment by AurevoirXavier** [comment]
Reopen if necessary.
