### ISSUE TITLE
Do we need the sudo?

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#1222]
> https://github.com/darwinia-network/darwinia/blob/f614277d9c1cc7945bfeed4c72ce64064668f738/.maintain/docker/Dockerfile#L11

**Comment by fewensa** [comment]
Yes, we can remove `sudo`, based on observations during this period, it does not require, If this is really needed, we add it later.

(polkadot docker image also not installed `sudo`)

**Comment by AurevoirXavier** [comment]
> Yes, we can remove `sudo`, based on observations during this period, it does not require, If this is really needed, we add it later.
> 
> (polkadot docker image also not installed `sudo`)

Please ensure that we have not used it anywhere.
