### ISSUE TITLE
Darwinia USDT

### ISSUE THREAD

**Issue by jiguantong** [darwinia-network/darwinia#1234]
## Pallets
- asset-manager
- orml-xtokens

## XCM config
- IsReserve
- AssetTransactor
- Trader

## Register USDT
symbol: ahUSDT
decimals: 6
Name: Tether USD
```
{
	parents: 1
	interior: X3(
		Parachain: 1000,
		PalletInstance: 50,
		GeneralIndex: 1984
	)
}
```

## Set UnitsPerSecond
25,000,000   0.1U for xcm execution fee.

## Erc20 token
Precompiles?
https://moonscan.io/token/0xFfFFfFff1FcaCBd218EDc0EbA20Fc2308C778080#code

## Limit
200k USDT:   200000000000

**Comment by hackfisher** [comment]
One more question, if the lease prior expires, can the sovereign account of the parachain withdraw the U from Assethub. If not, the end of lease period may affect user redemption of U from parachain, what's the plan B for this, should the parachain sovereign withdraw the U to other custody account elsewhere before leasing period?

Hope core and para thread can be adopted easily to cease concerns like this.

**Comment by jiguantong** [comment]
> One more question, if the lease period of the parachain expires, can the sovereign account of the parachain withdraw the U from Assethub. If not, the end of lease period may affect user redemption of U from parachain, what's the plan B for this, should the parachain sovereign withdraw the U to other custody account elsewhere before leasing period?
> 
> Hope Relaychain core and para thread can be adopted easily to cease concerns like this.

We should transfer assets in sovereignAccount to other custody account before leasing period. In the worst case that we fail to handle it before expiration, we can transfer the assets through governance on the corresponding chain. 

It seems difficult for the relay chain to handle this task, because the assets is on the different parachains, not the relay chain. Even if the relay chain can send XCM to the parachain to let it transfer the assets to a new custody account, the parachain can still refuse to do so because it has its own sovereignty.
