### ISSUE TITLE
The `try-runtime` and the `runtime-benchmarks` cannot be used simultaneously.

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#1246]
https://github.com/darwinia-network/darwinia/blob/336c98af839cacbc1163acc030b776f1edcfa6b1/runtime/darwinia/src/lib.rs#L95-L106

**Comment by AurevoirXavier** [comment]
@boundless-forest do you remember why we need this runtime version patch for benchmarking?

**Comment by boundless-forest** [comment]
https://github.com/darwinia-network/darwinia/pull/1158

> To make the benchmark call dispatch successful, the spec_version required to be the same as the hard-coded one in the messsage benchmark script. So introduced another VERSION under benchmark feature.
