### ISSUE TITLE
Check the deprecated balances apis

### ISSUE THREAD

**Issue by boundless-forest** [darwinia-network/darwinia#1247]
This issue created for tracking the potential incompatibilities caused by the [upcoming changes to the balances API](https://github.com/paritytech/polkadot-sdk/pull/1226
), including the darwinia's runtime, darwinia js, darwinia apps, etc.

**Comment by hackfisher** [comment]
Need to check and clean/housekeeping

https://github.com/darwinia-network/darwinia.js

**Comment by boundless-forest** [comment]
We have upgraded to the new balance APIs, so close it.
