### ISSUE TITLE
Darwinia & Pangolin ahUSDT

### ISSUE THREAD

**Issue by jiguantong** [darwinia-network/darwinia#1257]
https://github.com/darwinia-network/darwinia/issues/1234
# Pangolin
Pangolin PR: https://github.com/darwinia-network/darwinia/pull/1236
Batch call 
```
0x1a000c2d0000010300a10f0432058579285465746865722055534418616855534454060001000000000000000000000000000000012d0100010300a10f043205857940787d01000000000000000000000000010000002f0000010300a10f043205857900d0ed902e0000000000000000000000
```
- [x] Register Asset ahUSDT
```
# asset location
{parents: 1, (Parachain: 1000, PalletInstance: 50, GeneralIndex: 7777)}
# name
Tether USD
# symbol
ahUSDT
# decimals
6
# isSufficient
Yes
```
- [x] Set UnitsPerSecond: 25000000
- [x] Set AssetLimit: 200000000000
## HRMP
- [x] Pangolin > AssetHub
- [x] AssetHub > Pangolin
- [x] sufficient
## APP
- [x] Refer to https://apps.moonbeam.network/moonbeam/xcm
- [x] Test

# Darwinia
Darwinia PR: https://github.com/darwinia-network/darwinia/pull/1316
Batch call
```
0x1a000c2d0000010300a10f043205011f285465746865722055534418616855534454060001000000000000000000000000000000012d0100010300a10f043205011f40787d01000000000000000000000000010000002f0000010300a10f043205011f00d0ed902e0000000000000000000000
```
- [x] Add pallets
- [x] Register ahUSDT
```
# asset location
{parents: 1, (Parachain: 1000, PalletInstance: 50, GeneralIndex: 1984)}
# name
Tether USD
# symbol
ahUSDT
# decimals
6
# isSufficient
Yes
```
- [x] Set UnitsPerSecond: 4000000
- [x] Set AssetLimit: 200000000000
- [x] HRMP
- [ ] UI: Update min balance
- [x] Test

**Comment by AurevoirXavier** [comment]
We can move forward with this now.

**Comment by jiguantong** [comment]
## Test on Pangolin
### AssetHub > Pangolin
```
0x1f0803010100e52003000103009f33a4809aa708d7a399fedba514e0a0d15efa850304000002043205857900022d31010000000000
```
AssetHub: https://assethub-rococo.subscan.io/block/2900269?tab=event
Pangolin: https://pangolin.subscan.io/block/1527106?tab=event
### Pangolin > AssetHub
```
0x2e010300010300a10f04320585790002c2eb0b03010200a10f010044cb62d1d6cdd2fff2a5ef3bb7ef827be5b3e117a394ecaa634d8dd9809d560800
```
AssetHub: https://assethub-rococo.subscan.io/block/2900260?tab=event
Pangolin: https://pangolin.subscan.io/block/1527089?tab=event

**Comment by jiguantong** [comment]
There are some things to do after the runtime upgrade.

**Comment by AurevoirXavier** [comment]
@jiguantong Remember to update this.

**Comment by jiguantong** [comment]
# Test on Darwinia
## AssetHub > Darwinia
```
0x1f0803010100f91f03000103009f33a4809aa708d7a399fedba514e0a0d15efa850304000002043205011f00021bb7000000000000
```
AssetHub: https://assethub-polkadot.subscan.io/xcm_message/polkadot-18f85debf118602989724573d4eec11d3e904a30
Darwinia: https://darwinia.subscan.io/xcm_message/polkadot-18f85debf118602989724573d4eec11d3e904a30

## Darwinia > AssetHub
```
0x2e010300010300a10f043205011f0002127a0003010200a10f010044cb62d1d6cdd2fff2a5ef3bb7ef827be5b3e117a394ecaa634d8dd9809d560800
```

Darwinia: https://darwinia.subscan.io/xcm_message/polkadot-dcf28c1d607421fdce473e35202df97ffd614f18
AssetHub: https://assethub-polkadot.subscan.io/xcm_message/polkadot-dcf28c1d607421fdce473e35202df97ffd614f18
