### ISSUE TITLE
Enable Wrap Sync

### ISSUE THREAD

**Issue by boundless-forest** [darwinia-network/darwinia#1293]
As As https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-39/2277#low-impact-9 shows, the Wrap Sync feature is available for the parachain. Enabling this makes node operators life much faster and easier.

**Comment by AurevoirXavier** [comment]
Already included. I've been using this for a long time.

**Comment by AurevoirXavier** [comment]
And I can say it's not very stable yet. Eventually, it will become the default sync method.

**Comment by boundless-forest** [comment]
Have you ever tried this funtionality? I discussed this with @fewensa  this morning and it seems that the warp sync is not working as intended.

**Comment by AurevoirXavier** [comment]
> Have you ever tried this funtionality? I discussed this with @fewensa this morning and it seems that the warp sync is not working as intended.

As I said, it isn't quite stable yet. Need some patient and a good network enviroment.

**Comment by boundless-forest** [comment]
Nice, Thanks for your answer.

**Comment by fewensa** [comment]
> But I've tested it on Crab and Darwinia. It did work.

Yes, It's works. I tested it  use crab, this still requires a parachain data snapshot. but relay chain data sync is currently working as well.

**Comment by AurevoirXavier** [comment]
> Yes, It's works. I tested it use crab, this still requires a parachain data snapshot.

No need if everything goes smooth.
