### ISSUE TITLE
Genesis mismatch. Banned, disconnecting

### ISSUE THREAD

**Issue by stakeworks** [darwinia-network/darwinia#1325]
After upgrading from v6.4.0-4 to v6.5.0-1, I'm getting a lot of these report messages on bot Crab and Darwinia:

Report 12D3KooWHocwsvwBNxKsqeiH3SBzJ17vTDe7pv2iaA71uMX2Sd7f: -2147483648 to -2147483648. Reason: Genesis mismatch. Banned, disconnecting

And to a lesser extent: 
Trying to remove unknown reserved node 12D3KooWNeyKZaudpqRCyAz3NBRG6DRTLi51R7HFQGh7DHVhT4iU from SetId(3)

After upgrading and restarting the Crab node I was also getting these messages the first 5 minutes:
Sending fatal alert BadCertificate

OS: Ubuntu 20.04 LTS
Binary: v6.5.0-1

![image](https://github.com/darwinia-network/darwinia/assets/19406838/3443fec8-dd75-4a19-b652-60093aab32e6)

**Comment by boundless-forest** [comment]
Have you ever have trouble with this issue? @AurevoirXavier

**Comment by AurevoirXavier** [comment]
You are producing block. I don't think that's a problem. I guess it's just some warning log from the old-invalid nodes.

**Comment by stakeworks** [comment]
Thanks, I already suspected something like that. My nodes are producing blocks and they have the same number of peers as before the upgrade. On another Crab node I got these messages also, probably also old-invalid nodes:

![image](https://github.com/darwinia-network/darwinia/assets/19406838/a14ca978-c770-4475-a2dd-a7464d9b4fbc)
