### ISSUE TITLE
address type will covered normal SCALE-encoded type

### ISSUE THREAD

**Issue by freehere107** [darwinia-network/darwinia#135]
https://github.com/darwinia-network/darwinia/blob/1dfa6f14b7b40b3d5808f152159e8939720bec1e/types.json#L28
https://github.com/polkadot-js/api/issues/1630

**Comment by AurevoirXavier** [comment]
https://github.com/darwinia-network/darwinia/blob/1dfa6f14b7b40b3d5808f152159e8939720bec1e/core/sr-eth-primitives/src/lib.rs#L21 to EthAddress

https://github.com/darwinia-network/darwinia/blob/1dfa6f14b7b40b3d5808f152159e8939720bec1e/core/sr-eth-primitives/src/lib.rs#L22 to EthBlockNumber
