### ISSUE TITLE
Remember to registar.swap 2046 with 2003 on Polkadot by sending XCM during Lease 16 (Around  2024-04-09 ~ 2024-07-09)

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia#1383]
Planing to bid lease 16-23 using para 2003, and 16 will be the overlapping lease between 2046 and 2003.

2003 is already unlocked and send the pending swap to 2046.

After para 2003 successfully get leases 16-23, and polkadot goes in the lease 16, para 2046 must finish the swap by sending XCM to Polkadot to approve the swap, thus ensuring continuity of the lease.

Ref: https://wiki.polkadot.network/docs/learn-auction

**Comment by jiguantong** [comment]
sendXcmCall data
```
0x210001010002140004000000000700e40b540213000000000700e40b54020006000700f2052a01284603fe070000d3070000140d010004000100f91f
```

**Comment by jiguantong** [comment]
Use paraId manager to unlock and swap
1. https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/runtime/common/src/paras_registrar/mod.rs#L312
2. https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/runtime/common/src/paras_registrar/mod.rs#L566

**Comment by hackfisher** [comment]
https://darwinia2.subsquare.io/referenda/12
