### ISSUE TITLE
Support PINK

### ISSUE THREAD

**Issue by jiguantong** [darwinia-network/darwinia#1415]
- [x] Destroy old PINK (1028)
- [x] Upgrade runtime (https://github.com/darwinia-network/darwinia/pull/1416)
- [x] Register ahUSDT
- [x] *After 1028 is destroyed and runtime upgraded* register PINK call
```
0x2d0000010300a10f0432055c1050494e4b18616850494e4b0a000100000000000000000000000000000001
```
- [x] Test Transfer PINK from AssetHub to Darwinia
- [x] Test Transfer PINK from Darwinia to AssetHub

**Comment by AurevoirXavier** [comment]
```
0x1a00102d0000010300a10f043205011f285465746865722055534418616855534454060001000000000000000000000000000000012d0100010300a10f043205011f00093d00000000000000000000000000010000002f0000010300a10f043205011f00d0ed902e00000000000000000000002d0000010300a10f0432055c1050494e4b18616850494e4b0a000100000000000000000000000000000001
```

**Comment by jiguantong** [comment]
Batch call
- register ahUSDT
- setUnitsPerSecond for ahUSDT
- setAssetLimit for ahUSDT
- register PINK
- send XCM to AssetHub to transfer testing PINK

```
0x1a04142d0000010300a10f043205011f285465746865722055534418616855534454060001000000000000000000000000000000012d0100010300a10f043205011f00093d00000000000000000000000000010000002f0000010300a10f043205011f00d0ed902e00000000000000000000002d0000010300a10f0432055c1050494e4b18616850494e4b0a000100000000000000000000000000000001210001010100a10f020c00040000000002286bee130000000002286bee0004040000020432055c000700c817a80400010100dcff1219121687391353b17e798b10e87f6e578b2a01e032375f2f14a0712b57
```

**Comment by jiguantong** [comment]
## AssetHub > Darwinia
```
0x1f0803010100f91f03000103009f33a4809aa708d7a399fedba514e0a0d15efa8503080000020432055c000700c817a804000002043205011f0002093d000100000000
```
AssetHub: https://assethub-polkadot.subscan.io/xcm_message/polkadot-3c6298781b6471e0504ef0331977e5ecb9154191
Darwinia: https://darwinia.subscan.io/xcm_message/polkadot-3c6298781b6471e0504ef0331977e5ecb9154191

## Darwinia > AssetHub
```
0x2e05030800010300a10f0432055c000700d6117e0300010300a10f043205011f0082b92a000100000003010200a10f010102dcff1219121687391353b17e798b10e87f6e578b2a01e032375f2f14a0712b5700
```
Darwinia: https://darwinia.subscan.io/xcm_message/polkadot-f5f0abceab317c3c9d42a1312fa46bd566b56a01
AssetHub: https://assethub-polkadot.subscan.io/xcm_message/polkadot-f5f0abceab317c3c9d42a1312fa46bd566b56a01
