### ISSUE TITLE
uint8 in staking precompile is too small?

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia#1422]
https://github.com/darwinia-network/darwinia/blob/7d1ad6f4725ca41ea2ff5066aaffedc94505547f/precompile/metadata/abi/staking.json#L141

**Comment by AurevoirXavier** [comment]
https://github.com/darwinia-network/darwinia/blob/7d1ad6f4725ca41ea2ff5066aaffedc94505547f/runtime/darwinia/src/pallets/deposit.rs#L48

**Comment by hackfisher** [comment]
Becareful about the vec

```
pub type Deposits<T: Config> =
		StorageMap<_, Blake2_128Concat, T::AccountId, BoundedVec<Deposit, T::MaxDeposits>>;
```
Does it need migration if change the size?

**Comment by hackfisher** [comment]
We may also choose to not change for now and tell the user to use another account for depositing by telling him that this is the limitation of the protocol

**Comment by hackfisher** [comment]
> https://github.com/darwinia-network/darwinia/blob/7d1ad6f4725ca41ea2ff5066aaffedc94505547f/runtime/darwinia/src/pallets/deposit.rs#L48

This do not need change for this time.
