### ISSUE TITLE
Clean or burn the balance of deprecated account b'root' used for s2s RootAccountForPayments

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia#1451]
https://crab.subscan.io/account/0x726f6f7400000000000000000000000000000000

The balance in it was used for pay s2s fees when the origin is from some substrate origin such as Origin Root, it is used anymore so its balance can be cleaned by sending back to treasury or being burned.

It seems that no balance in the same account on Darwinia:
https://darwinia.subscan.io/account/0x726f6f7400000000000000000000000000000000

**Comment by AurevoirXavier** [comment]
What about conducting referenda?
