### ISSUE TITLE
Log discrepancies for the same block between two requests within a specified interval.

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia#1473]
Detected invalid logs returned by the RPC when proceed finalisation.

https://github.com/ponder-sh/ponder/blob/bc42e8189600df581241a72c46392c144ee9c06b/packages/core/src/sync-realtime/service.ts#L666
```
  /**
   * Check to see if re-requesting logs that we have locally will return a different result.
   * If this occurs, treat it as a reorg.
   */
```

[0.4.2_trace_ponder.log](https://github.com/darwinia-network/darwinia/files/14975261/0.4.2_trace_ponder.log)

Related to mapping syncing in frontier?

**Comment by boundless-forest** [comment]
Fixed by https://github.com/darwinia-network/darwinia/pull/1597
