### ISSUE TITLE
Possibility of using offchain-worker to implement relay worker?

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#148]

**Comment by wuminzhe** [comment]
[https://www.youtube.com/watch?v=Fm_x84v8uF0](https://www.youtube.com/watch?v=Fm_x84v8uF0)
[https://github.com/jimmychu0807/substrate-offchain-pricefetch](https://github.com/jimmychu0807/substrate-offchain-pricefetch)

[https://gnunicorn.github.io/substrate-offchain-cb/](https://gnunicorn.github.io/substrate-offchain-cb/)

**Comment by HackFisher** [comment]
Duplicate with #289
