### ISSUE TITLE
Review places that create reserved in balance, and why it is not counted in reducible_balance

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia#1484]
https://github.com/paritytech/polkadot-sdk/blob/ffbce2a817ec2e7c8b7ce49f7ed6794584f19667/substrate/frame/balances/src/impl_fungible.rs#L47-L72

<img width="946" alt="image" src="https://github.com/darwinia-network/darwinia/assets/1070122/eab21cfd-62b8-4b3e-8128-067c0679490f">

0xC1c8F6Ef43b39C279417E361969d535F2a20b92e

https://github.com/darwinia-network/frontier/blob/9c50b611ce93033cf2766281c8c38c73757ec502/frame/evm/src/lib.rs#L897

_Originally posted by @hackfisher in https://github.com/darwinia-network/darwinia/issues/1483#issuecomment-2074056943_

**Comment by hackfisher** [comment]
Another report from @1022ranji 0xe59261f6D4088BcD69985A3D369Ff14cC54EF1E5

<img width="1196" alt="image" src="https://github.com/darwinia-network/darwinia/assets/1070122/68e25d92-98a8-4637-8c34-b07ae87cec1a">

This causes metamask show usable balance but no able to pay gas.

**Comment by hackfisher** [comment]
Related:

https://github.com/paritytech/polkadot-sdk/issues/1833

https://github.com/paritytech/polkadot-sdk/pull/2292

**Comment by hackfisher** [comment]
> Related:
> 
> [paritytech/polkadot-sdk#1833](https://github.com/paritytech/polkadot-sdk/issues/1833)
> 
> [paritytech/polkadot-sdk#2292](https://github.com/paritytech/polkadot-sdk/pull/2292)

The substrate current using is inconsistency with the new definition in the referred issue.

![image (5)](https://github.com/darwinia-network/darwinia/assets/1070122/7225b83c-482d-46d2-bd42-1fa409557cd1)

**Comment by hackfisher** [comment]
Use https://github.com/polkadot-evm/frontier/pull/1282 to fix.

**Comment by boundless-forest** [comment]
Fixed in the runtime 6630. Close it.
