### ISSUE TITLE
Support asynchronous backing

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia#1488]
https://wiki.polkadot.network/docs/maintain-guides-async-backing

https://forum.polkadot.network/t/paritytech-update-for-april-2024/7646

**Comment by hujw77** [comment]
If the block time is changed to 6 seconds, it needs to be synchronized to the tally platform backend, which is currently configured for 12 seconds. cc

**Comment by AurevoirXavier** [comment]
> If the block time is changed to 6 seconds, it needs to be synchronized to the tally platform backend, which is currently configured for 12 seconds. cc

IIRC KTON staking also utilizes block time?

**Comment by AurevoirXavier** [comment]
Might need to patch Moonbeam dependencies.

https://github.com/moonbeam-foundation/moonbeam/pull/2784

@boundless-forest

**Comment by boundless-forest** [comment]
If the block time is reduced to 6s, a migration for the `acount-migration` may be needed. I remember that some locks are tight with block time.

**Comment by AurevoirXavier** [comment]
> If the block time is reduced to 6s, a migration for the `acount-migration`, `staking` and `deposit` may be needed. I remember that some locks are tight with block time.

No longer necessary after DIP-6.
