### ISSUE TITLE
Darwinia DOT

### ISSUE THREAD

**Issue by jiguantong** [darwinia-network/darwinia#1496]
- [x] Upgrade Runtime(https://github.com/darwinia-network/darwinia/pull/1499)
- [x] Register DOT
 - [x] SetUnitsPerSecond
 ```
0x1a04082d000001000c444f540c444f540a0001000000000000000000000000000000012d0100010000286bee00000000000000000000000002000000
```
- [x] Transfer DOT from Polkadot to Darwinia
- [x] Transfer DOT from Darwinia to Polkadot
- [x] Fee

**Comment by jiguantong** [comment]
Polkadot >  Darwinia
```
weight_per_second: 1000000000000

units_per_second for DOT: 4000000000

fee = units_per_second * baseXcmWeight * 5 / units_per_second 

fee = 4000000000 * 1_000_000_000 * 5 / 1000000000000 = 20000000 = 0.002 DOT
```

**Comment by jiguantong** [comment]
## Transfer DOT from Rococo to Pangolin
```
0x630803000100e52003000103009f33a4809aa708d7a399fedba514e0a0d15efa850304000000000b005039278c040000000000
```

**Comment by AurevoirXavier** [comment]
Status? @jiguantong

**Comment by jiguantong** [comment]
### Darwinia > Polkadot
https://darwinia.subscan.io/xcm_message/polkadot-28874f266876a60eee9b062f41d986ca72735171
### Polkadot > Darwinia
https://darwinia.subscan.io/xcm_message/polkadot-5807bb2d2e2713f20d6e2b744e905bb5f2d299fb
