### ISSUE TITLE
Test if non zero tx value works or not in forward_transact

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia#1517]
https://github.com/darwinia-network/darwinia/blob/2dadcd456ab2d5b0f87af634d8bac979484300d7/pallet/staking/src/lib.rs#L1033

**Comment by hackfisher** [comment]
https://github.com/darwinia-network/kton-staker/blob/51fcac7e4ce2c4d80765c98bc544554b9f289b2e/src/staking/KtonDAOVault.sol#L41

**Comment by boundless-forest** [comment]
I checked the implementation about the forward_transact, it supports non-zero value, the behaviour is no different compared to the common usage. Any problems found here?

**Comment by boundless-forest** [comment]
I think this can be closed.
