### ISSUE TITLE
Review: Check ALL Usage of `unwrap()`

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#153]
Unwrap panic could cause node hanging.

Like #151.

**Comment by clearloop** [comment]
The `panic` part currently exists at [chainrelay/eth/relay][1], `map_err` into [`Receipt`][2],

```rust
let receipt = rlp::decode(&value).map_err(|_| "Deserialize Receipt - FAILED")?;
```

It might be safe now? or probably need more tests for the `decode` method?

[1]: https://github.com/darwinia-network/darwinia/blob/bee19e38baaa62cb529fd839e16585bfe2340c43/frame/chainrelay/eth/relay/src/lib.rs#L366
[2]: https://github.com/darwinia-network/darwinia/blob/bee19e38baaa62cb529fd839e16585bfe2340c43/primitives/sp-eth-primitives/src/receipt.rs#L43

**Comment by AurevoirXavier** [comment]
Move to #353.

**Comment by HackFisher** [comment]
> The `panic` part currently exists at [chainrelay/eth/relay](https://github.com/darwinia-network/darwinia/blob/bee19e38baaa62cb529fd839e16585bfe2340c43/frame/chainrelay/eth/relay/src/lib.rs#L366), `map_err` into [`Receipt`](https://github.com/darwinia-network/darwinia/blob/bee19e38baaa62cb529fd839e16585bfe2340c43/primitives/sp-eth-primitives/src/receipt.rs#L43),
> 
> ```rust
> let receipt = rlp::decode(&value).map_err(|_| "Deserialize Receipt - FAILED")?;
> ```
> 
> It might be safe now? or probably need more tests for the `decode` method?

Didn't get it, do you mean it could panic in ```decode```? 

map_error is used to avoid no handling of Error?

**Comment by AurevoirXavier** [comment]
No, this just map `decode err` into `&str err`. 
https://doc.rust-lang.org/std/result/enum.Result.html#method.map_err

**Comment by clearloop** [comment]
> Didn't get it, do you mean it could panic in decode?
>
> map_error is used to avoid no handling of Error?

Sorry for that, I forget what I was thinking about at that time, but `map_err` only can modify `err` but not stop panicking, ref to rust doc:

```rust
fn stringify(x: u32) -> String { 
  format!("error code: {}", x) 
}

let x: Result<u32, u32> = Err(13);
assert_eq!(x.map_err(stringify), Err("error code: 13".to_string()));
```

It's still an `Err` after we `map` it, and `?` will pass it to the caller function, so we should check if the caller function handles the `Err` well.

**Comment by AurevoirXavier** [comment]
No, we just need to raise it up. Substrate will handle this.

**Comment by HackFisher** [comment]
The key idea here is that runtime cannot ```panic!``` but error handling/mapping is acceptable, so be careful about functions which can cause panic, such as ```unwrap()```

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/darwinia/wiki/Best-Practice-for-Darwinia-Security-Review
