### ISSUE TITLE
How to Clean Staking System?

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#154]
The `withdraw_unbonded` was removed.

How to trigger the `kill_stash` to remove the 'empty' account and keep the staking system clean?

```rust
StakingLedger {
	active_ring/kton: zero,
	ring/kton_lock: all expired,
	...
}
```

**Comment by yanganto** [comment]
The `kill_stash` is called on the account has zero balance(`on_free_balance_zero`), or the dust account has every low free balance(`on_free_too_low`).

**Comment by yanganto** [comment]
The `bond` do two things 
- let two accounts has roles, `stash` and `controller`
- some values(Ring and Kton) are locked.

And the `unbond` process only do one thing
- free the lock of some values

There is not an easy way to clear the relation between `stash` and `controller`.
The relation between `stash` and `controller` exist, the stacking ledge may be still exist for clarity.
If we want to remove stacking ledge to shrink the storage in the future blocks, 
we need some way to break the relation between of `stash` and `controller`.

Here is the proposal.
In the `unbond` process, some values unlock.
Once there are none values locked, the relation between `stash` and `control` will be break, 
and these account will become a normal account, 
such that the stacking ledge can be removed to save the storage.

Besides these accounts are bonded, 
the user still can use `bond_extra` to bond more values to keep this relation.

**Comment by AurevoirXavier** [comment]
- origin src:
	- https://github.com/darwinia-network/substrate/blob/darwinia-develop/srml/staking/src/lib.rs#L783
	- https://github.com/darwinia-network/substrate/blob/darwinia-develop/srml/staking/src/lib.rs#L842

**Comment by yanganto** [comment]
The original operations of Substrate are `unbond` and `withdraw_unbond`.  We can just let this process more smart.  People can `unbond` to free the lock of values, and it will be auto withdraw when there is no value locked.
