### ISSUE TITLE
Check the gas, pov size configs in the async backing

### ISSUE THREAD

**Issue by boundless-forest** [darwinia-network/darwinia#1551]
After the chain runtime transitioned to async backing mode, the block time shortened to 6 seconds. However, the allocated block execution has increased from 500 milliseconds to 2000 milliseconds. This means the maximum ref time for the block extrinsic has become four times greater than before. Does that imply a larger block throughput for the chain? The answer is probably not. The current block throughput is constrained by two factors: ref_time and proof_size. The proof_size has not changed between the async backing mode and before. Simply increasing the ref_time may not enhance the overall throughput for the block; it only allows the block to include more calculation-intensive tasks. However, for tasks that involve significant storage access, it will still be restricted by the proof size.

The block_gas_limit reflects the block throughput from the Ethereum perspective. It is derived from the maximum block weight and will change as the chain's throughput (both ref_time and proof_size) increases.

Q: After the transition to async backing, do we need to increase the block_gas_limit?

As I mentioned earlier, simply increasing the ref_time does not necessarily lead to an increase in block throughput due to the proof_size. Therefore, I believe there is no need to raise the gas limit at this time. This issue was created to double-check if anything is overlooked in the transition. I think it would be a good opportunity to increase the current block gas limit once the chains support storage proof size reclaim.

**Comment by AurevoirXavier** [comment]
I believe we have reached a conclusion for this.
