### ISSUE TITLE
Unable to determine type from DepositInfo

### ISSUE THREAD

**Issue by AlexChien** [darwinia-network/darwinia#16]
https://github.com/darwinia-network/darwinia/blob/8d5c84d6b97759be9b9ed540730fc6e0ca04c8d1/types.json#L15

Should this be `"deposit_list": "Vec<IndividualDeposit>"`?

**Comment by hammeWang** [comment]
@AlexChien yes.

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/darwinia/pull/17
