### ISSUE TITLE
KtonStaking is not distributing rewards after latest runtime upgrade on Crab

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia#1604]
https://crab-scan.darwinia.network/address/0x652182C6aBc0bBE41b5702b05a26d109A405EAcA?tab=txs

**Comment by hackfisher** [comment]
https://github.com/darwinia-network/darwinia/blob/3b73ea205a92861319b26cc19f88c44e8f3b8bc6/pallet/staking/src/lib.rs#L298

https://github.com/darwinia-network/darwinia/blob/e9c5fad5b1345dcb3d3576e2e59384aab467d045/pallet/staking/src/lib.rs#L324


`KtonRewardDistributionContract` is renamed to `KtonStakingContract`, but there was no related migration in the runtime upgrade.


Same issues exist for the upcoming Darwinia runtime upgrade.

**Comment by sonoferin2000** [comment]
Here are some considerations for addressing this:

    Contract Address Consistency: Check if the contract address remains the same. If it does, renaming might only affect readability or the user interface, and the underlying functionality should remain intact.

    Alias Mapping: Implement alias mapping in the system that references the new KtonStakingContract name without breaking older references to KtonRewardDistributionContract. This can be a temporary solution until a full migration is possible.

    Runtime Compatibility: For the upcoming Darwinia runtime upgrade, ensure that any references to the old contract name (KtonRewardDistributionContract) are updated in the runtime code, even if there is no migration script. You may need to manually adjust where the new KtonStakingContract is invoked, ensuring backward compatibility.
