### ISSUE TITLE
Review: Compute Kton Return When Value Too Small?

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#162]
Around 0.00003 Ring, function returns 0.

Currently, I set a limitation on [Kton slash](https://github.com/darwinia-network/darwinia/blob/develop/srml/staking/src/lib.rs#L782). And the Kton reward?

**Comment by HackFisher** [comment]
This relates to corner cases that the deposited RING amount is too small?

Require reviewing the code

**Comment by AurevoirXavier** [comment]
> This relates to corner cases that the deposited RING amount is too small?
> 
> Require reviewing the code

https://github.com/darwinia-network/darwinia/blob/develop/frame/staking/src/lib.rs#L1362
