### ISSUE TITLE
[Darwinia Next Runtime Upgrade Check] Will 20M unstaking limit be an issue for migration?

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia#1638]
Will 20M unstaking limit be an issue for migration?

_Originally posted by @hackfisher in https://github.com/itering/internal-security-audit/issues/140#issuecomment-2453021076_

**Comment by hujw77** [comment]
https://github.com/darwinia-network/darwinia/blob/7ed9ae01f10a7d0cd99af9b6ac73de0518856bf8/pallet/staking/src/lib.rs#L75-L76
