### ISSUE TITLE
staking: automatically generate GenesisTime to the genesis block's time?

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#171]
There is a `GenesisTime` config in staking module, can it be removed?

**Comment by readlnh** [comment]
You mean config in `mock.rs`? As we don't use `GenesisTime` in tests now,  there's no effects if we remove the config and change it to `type GenesisTime = ();`. However, i'm not sure wheather it is needed if we implement the [current_total_payout_for_duration](https://github.com/darwinia-network/darwinia/blob/develop/srml/staking/src/mock.rs#L484) later.

**Comment by AurevoirXavier** [comment]
The config in runtime. We need the GenesisTime for inflation.

**Comment by HackFisher** [comment]
It is included in the genesis config file as part of runtime.
