### ISSUE TITLE
Eth backing: Should we use saturating_sub or checked_sub?

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#174]
```
<KtonLocked<T>>::mutate(|l| {
				*l = l.saturating_sub(redeemed_kton);
			});
```

**Comment by AurevoirXavier** [comment]
We can change `mutate` to `get` and `put`.

And `check_sub` the get value.

Change the writing operation logic(order), once the `check_sub` return `None` make sure nothing write to the chain.
