### ISSUE TITLE
Offline Slash Strategy

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#175]
~~It seems that in the latest pre-release tag v0.4.1, slash does not automatically happen if the validator do something bad or wrong.~~

~~What's missing part of the current slash understanding and design?~~

**Comment by AurevoirXavier** [comment]
Relate PR: https://github.com/paritytech/substrate/pull/3322

Handled:

https://github.com/darwinia-network/darwinia/blob/d1397ed066a876a37b60553abbbb3976a1fff195/node/runtime/src/lib.rs#L248

https://github.com/darwinia-network/substrate/blob/darwinia-develop/srml/im-online/src/lib.rs#L565

<img width="2502" alt="offline report" src="https://user-images.githubusercontent.com/16152305/71225091-65a64380-2312-11ea-8459-4202a7fda549.png">

---

I'll do more tests.

Seems the validator doesn't lose power.

**Comment by AurevoirXavier** [comment]
<img width="2560" alt="slash zero" src="https://user-images.githubusercontent.com/16152305/71226889-6b068c80-2318-11ea-8184-a5e49468e53c.png">

Slash zero, `continue`d.

**Comment by AurevoirXavier** [comment]
relate https://github.com/darwinia-network/darwinia/pull/187
