### ISSUE TITLE
Staking: Consider using Nicks Module for validators nick name

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#176]
Can do this refactoring after the release and upgrade of substrate 2.0?

**Comment by AurevoirXavier** [comment]
**2 ways to achive this**
	1. user set name manually in web-wallet after the *validate* operation
	2. call [set_name](https://github.com/paritytech/substrate/blob/master/frame/nicks/src/lib.rs#L145) in *validate*

**Comment by HackFisher** [comment]
> **2 ways to achive this**
> 
> 1. user set name manually in web-wallet after the _validate operation_
> 2. call [set_name](https://github.com/paritytech/substrate/blob/master/frame/nicks/src/lib.rs#L145) in _validate function_

Prefer 1, call set name seperately, not within staking module
