### ISSUE TITLE
Security: Check all the side effects caused by Err

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#177]
https://substrate.dev/docs/en/overview/transaction-lifecycle

> Remember that with Substrate, token transfers are not the only state transitions: any information can be written to a block. execute_block should never panic, and if a call to a module returns Err, it will be finalized and changes to storage will not be reverted. This is because reverting changes would require that each node copy storage at every block.

> When you are going to modify storage, the best practice is to do every check necessary to ensure that the call will succeed, execute all the storage changes, and finally emit an event so you know that the function has not returned early. For an example, see the transfer (code) function in the balances module - all checks are performed before touching storage.

> If you are designing your own modules, you have the responsibility to ensure that invalid extrinsics never panic and never modify module state when returning Err. A correctly implemented module may also secure a bond to penalize malicious parties from submitting invalid extrinsics in the first place (preventing DoS attacks).

https://substrate.dev/substrate-collectables-workshop/#/1/storing-a-value?id=result

**Comment by AurevoirXavier** [comment]
https://github.com/paritytech/substrate/issues/1791

**Comment by wuminzhe** [comment]
I suggest prefixing the methods that modify chain state.

**Comment by AurevoirXavier** [comment]
The methods below
https://github.com/darwinia-network/darwinia/blob/develop/srml/staking/src/lib.rs#L1271
and
https://github.com/darwinia-network/darwinia/blob/develop/srml/staking/src/lib.rs#L1136
are mutables.

**Comment by HackFisher** [comment]
Moved to #353 and wiki: https://github.com/darwinia-network/darwinia/wiki/Best-Practice-for-Darwinia-Security-Review
