### ISSUE TITLE
Extrinsics Logic

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#186]
## Presudo

- currently:
	```rust
	bond(stash, controller, want_to_bond, ...);
	
	fn bond() {
		...
		
		// adjust bond value automatically
		bond_value = min(stash_free_balance, want_to_bond);

		...
	}

	bond succeedd
	```
- proposal:
	```rust
	bond(stash, controller, want_to_bond, ...);
	
	fn bond() {
		...
		
		if stash_free_balance < want_to_bond {
			return Err("Stash Free Balance - NOT ENOUGH");
		}

		...
	}

	bond failed
	```

Same logic can be found in `bond_extra`, `deposit_extra`, `unbond`...

**Comment by wuminzhe** [comment]
I prefer the proposal way.

**Comment by AurevoirXavier** [comment]
Substrate way: https://github.com/paritytech/substrate/blob/master/frame/staking/src/lib.rs#L877

**Comment by HackFisher** [comment]
Let's simply follow the convention from substrate:

https://github.com/paritytech/substrate/blob/master/frame/staking/src/lib.rs#L904
