### ISSUE TITLE
node client sync block fail

### ISSUE THREAD

**Issue by freehere107** [darwinia-network/darwinia#190]
1. Just one node can output block
2. Node client sync block fail, p2p port can not connect

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/darwinia/commit/b02dbd4

https://github.com/darwinia-network/darwinia/commit/eb39a50


@AurevoirXavier can connect after replace cli with substrate-cli.

**Comment by HackFisher** [comment]
@AurevoirXavier Can check that only one validator can produce block is related to minimum validator requirement settings or not?

> Just one node can output block

**Comment by HackFisher** [comment]
> @AurevoirXavier Can check that only one validator can produce block is related to minimum validator requirement settings or not?
> 
> > Just one node can output block

Related to this: 

https://github.com/darwinia-network/darwinia/blob/develop/node/cli/src/chain_spec.rs#L339
```
fn icefrog_config_genesis() -> GenesisConfig {
		darwinia_genesis(
			vec![get_authority_keys_from_seed("Alice")],
			get_account_id_from_seed::<sr25519::Public>("Alice"),
			None,
			true,
		)
	}
```

**Comment by freehere107** [comment]
Need test ``not upgrade`` node can sync block data

**Comment by AurevoirXavier** [comment]
<img width="1259" alt="telemetry" src="https://user-images.githubusercontent.com/16152305/71457690-1ceefe80-27da-11ea-986d-31919a874be9.png">

**Comment by AurevoirXavier** [comment]
1. clean the old data before booting up 
2. this can be configured
