### ISSUE TITLE
Replace fraction stuffs with Perquintil

### ISSUE THREAD

**Issue by readlnh** [darwinia-network/darwinia#191]
https://github.com/darwinia-network/darwinia/blob/368a8d3b1352e059bb7cf5877e776e25843fb1ca/srml/staking/src/lib.rs#L1556

Since `total_payout` may be larger than 10,000,000,000, should we consider replace Perbill with Perquintil?

**Comment by readlnh** [comment]
https://github.com/darwinia-network/darwinia/pull/183/commits/8c72b066d28e5804a72a7416a7257873e847ad8b 
Now the error rate is only 100.

**Comment by AurevoirXavier** [comment]
close via #183
