### ISSUE TITLE
CI for Develop Branch

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#199]
https://travis-ci.org/darwinia-network/darwinia/builds/629607549?utm_source=github_status&utm_medium=notification

**Comment by AurevoirXavier** [comment]
try fix: #201

**Comment by AurevoirXavier** [comment]
Require: CI Build for Develop Branch

@freehere107

**Comment by freehere107** [comment]
fix #204

**Comment by HackFisher** [comment]
The latest commit didn't build, and the travis link is pointing to AurevoirXavier's repository?

```
image:https://travis-ci.org/AurevoirXavier/darwinia.svg[Build Status (Travis CI),link=https://travis-ci.org/AurevoirXavier/darwinia]
```

**Comment by AurevoirXavier** [comment]
I'll update it
