### ISSUE TITLE
Upgrade to the latest substrate master and version 

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#209]

**Comment by AurevoirXavier** [comment]
deps from https://github.com/darwinia-network/substrate/tree/master?

**Comment by HackFisher** [comment]
> deps from https://github.com/darwinia-network/substrate/tree/master?
> 
> upgrade the anchor version?

Yes, anchor dep to substrate master branch or substrate 2.0 after it is released.

**Comment by AurevoirXavier** [comment]
First try base on https://github.com/paritytech/substrate/commit/c2fccb36ffacd118fc3502aa93453580a07dc402
