### ISSUE TITLE
Failed to submit extrinsic: Transaction pool error: Too low priority (49682067 > 25383433)

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#217]
<img width="879" alt="icefrog-issue" src="https://user-images.githubusercontent.com/1070122/71662640-2acdf200-2d8d-11ea-9234-f5767b224daf.png">

**Comment by AurevoirXavier** [comment]
https://github.com/darwinia-network/darwinia/issues/42
https://github.com/paritytech/substrate/issues/2312

**Comment by HackFisher** [comment]
Need to check before next testnet release

**Comment by AurevoirXavier** [comment]
How to reproduce this?

**Comment by HackFisher** [comment]
reopen if reproducible

**Comment by clearloop** [comment]
[#10][0]

---


## eth_backing::redeem

For the test of the redeem process, I had succeeded at the first serval times, and then keep panic: 

```
 𝝺 ts-node relay.ts                         
[ info ] init darwinia account 🧙‍♂️
[ success ]: reset header succeed! 📦
[ info ] the tx hash of reset is 0xc1db273d86d6f4973b42b94327da0013fbf4afda07cc9704861b675251439026
[ success ]: relay header succeed! 🎉
[ info ] the tx hash of relay is 0x1217a40202aaa530d481641f1f9d41a7b217e73ab9bb305cc13b61b915062bf0
[ success ]: now we own 99999874144428 RING 💰
2020-03-26 20:49:46        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1014: Priority is too low: (108076489 vs 12507473): The transaction has too low priorit
[ error ]: redeem receipt failed!
```

It still happens when I cleared the Darwinia's database and restart it again.

[0]: https://github.com/darwinia-network/darwinia-offchain-tools/pull/10
