### ISSUE TITLE
Block import error: Execution(Wasmi(Trap(Trap { kind: Unreachable })))

### ISSUE THREAD

**Issue by wskyok** [darwinia-network/darwinia#220]
2020-01-03 21:46:45 Block import error:
Execution(Wasmi(Trap(Trap { kind: Unreachable })))
Hash: given=5587f508ec1a9ebbfb804c82afd65ad4865ebb572a8b7c5a27ee40a483f773bf, expected=e288d48981b55d480a2bfbfc3c648a330550a4556bc79ebdec9acb7ce91c4e14

====================

Version: 0.4.6-0174b00-x86_64-linux-gnu

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
   2: std::panicking::begin_panic
   3: srml_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
   4: node_runtime::api::dispatch
   5: std::panicking::try::do_call
   6: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:79
   7: substrate_executor::native_executor::safe_call
   8: std::thread::local::LocalKey<T>::with
   9: <node_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch
  10: std::thread::local::LocalKey<T>::with
  11: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_aux
  12: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_call_with_native_else_wasm_strategy
  13: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_using_consensus_failure_handler
  14: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state
  15: substrate_client::client::Client<B,E,Block,RA>::lock_import_and_run::{{closure}}
  16: <&substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
  17: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
  18: <substrate_consensus_babe::BabeBlockImport<B,E,Block,I,RA,PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
  19: substrate_consensus_common::import_queue::import_single_block
  20: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  21: futures_util::future::chain::Chain<Fut1,Fut2,Data>::poll
  22: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  23: futures_executor::thread_pool::PoolState::work
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
  25: std::panicking::try::do_call
  26: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:79
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/da3629b05f8f1b425a738bfe9fe9aedd47c5417a/src/liballoc/boxed.rs:1015
  29: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/da3629b05f8f1b425a738bfe9fe9aedd47c5417a/src/liballoc/boxed.rs:1015
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  30: start_thread
  31: __clone

Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', /home/xavier/.cargo/git/checkouts/substrate-a7fa553ead635512/d2c4b0d/srml/executive/src/lib.rs:277

This is a bug. Please report it at:

        https://github.com/darwinia-network/darwinia/issues/new

**Comment by AurevoirXavier** [comment]
dup #213
