### ISSUE TITLE
Type of `validator_payment_ratio` in struct `ValidatorPrefs`

### ISSUE THREAD

**Issue by readlnh** [darwinia-network/darwinia#224]
Now the type of `validator_payment_ratio` in `ValidatorPrefs` is `u32`, should we change it to `Perbill`?

**Comment by AurevoirXavier** [comment]
No, I change it in https://github.com/darwinia-network/darwinia/commit/129416a2d4ec67e16a3e673f8dff297a861cfda4.

Much easier to understand for front-end.

**Comment by HackFisher** [comment]
Related https://github.com/darwinia-network/darwinia/pull/212
