### ISSUE TITLE
用VPN科学上网，当cargo build时出现网络问题怎么解决？

### ISSUE THREAD

**Issue by frighter518** [darwinia-network/darwinia#225]
C:\darwinia> cargo build
    Updating crates.io index
warning: spurious network error (2 tries remaining): failed to send request: 操
作超时
; class=Os (2)
warning: spurious network error (1 tries remaining): failed to send request: 操
作超时
; class=Os (2)
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to send request: 操作超时
; class=Os (2)

**Comment by AurevoirXavier** [comment]
VPN 问题或者命令行没有被代理到

不属于本项目问题
