### ISSUE TITLE
Icefrog `reset_genesis_header` failed.

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#227]
https://icefrog.subscan.io/extrinsic/116744-2

**Comment by AurevoirXavier** [comment]
fail in `re_compute_hash`

make sure header data is ok

**Comment by HackFisher** [comment]
> fail in `re_compute_hash`
> 
> make sure header data is good
> 
> https://icefrog.subscan.io/extrinsic/34509-2
> https://icefrog.subscan.io/extrinsic/116744-2
> 
> different `seal`

https://icefrog.subscan.io/extrinsic/119759-2

This extrinc has the same data with https://icefrog.subscan.io/extrinsic/34509-2
