### ISSUE TITLE
kton deposit/deposit extra 失败

### ISSUE THREAD

**Issue by feilun-feilun** [darwinia-network/darwinia#23]
![QQ20190702-001](https://user-images.githubusercontent.com/49551621/60509752-4bdf5880-9d00-11e9-9b35-5f41a3004d99.png)
![QQ20190702-002](https://user-images.githubusercontent.com/49551621/60509754-4c77ef00-9d00-11e9-9c97-8048447d347e.png)
![QQ20190702-003](https://user-images.githubusercontent.com/49551621/60509755-4d108580-9d00-11e9-9ee1-0a29b51ad2a1.png)
![QQ20190702-004](https://user-images.githubusercontent.com/49551621/60509756-4d108580-9d00-11e9-92cb-993a7cae0fd9.png)
以上为失败的操作过程截图
之前第一次操作成功，之后连续失败，多次操作中，有一次50万12个月成功，之后再为成功兑换kton。

节点feilun提交

**Comment by hammeWang** [comment]
可以提供你的账户地址吗
