### ISSUE TITLE
`CurrencyToVote` to `PowerToVote`

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#238]
not finish in #94

**Comment by AurevoirXavier** [comment]
will be fix in #218

**Comment by AurevoirXavier** [comment]
`TOTAL_POWER` is `1_000_000_000`.

```rust
impl PowerToVoteHandler {
	fn factor() -> Power {
		(TOTAL_POWER / u64::max_value() as Power).max(1)
	}
}

impl Convert<Power, u64> for PowerToVoteHandler {
	fn convert(x: Power) -> u64 {
		(x / Self::factor()) as u64
	}
}

impl Convert<u128, Power> for PowerToVoteHandler {
	fn convert(x: u128) -> Power {
		x * Self::factor()
	}
}
```

So, `Power : Votes = 1 : 1`.

Actually `Power` is `Votes`, the `Handler` can be removed.

**Comment by AurevoirXavier** [comment]
darwinia-support

```rust
pub trait CurrencyPowerConvert<Currency, Power> {
	fn to_currency(power: Power, pool: Currency) -> Currency;
	fn to_power(currency: Currency, pool: Currency) -> Power;
}
```


impl.rs

```rust
pub struct PowerToVoteHandler;

impl<RingCurrency> CurrencyPowerConvert<RingCurrency, Power> for PowerToVoteHandler 
where
	RingCurrency: SimpleArithmetic,
{
	fn to_currency(power: Power, pool: Currency) -> Currency {
		unimplemented!()
	}
	
	fn to_power(currency: Currency, pool: Currency) -> Power {
		unimplemented!()
	}
}

impl<KtonCurrency> CurrencyPowerConvert<KtonCurrency, Power> for PowerToVoteHandler
where
	KtonCurrency: SimpleArithmetic,
{
	fn to_currency(power: Power, pool: Currency) -> Currency {
		unimplemented!()
	}
	
	fn to_power(currency: Currency, pool: Currency) -> Power {
		unimplemented!()
	}
}
```

**Comment by HackFisher** [comment]
> @HackFisher,
> 
> Handler Design:
> 
> ```rust
> // darwinia-support lib.rs
> pub trait CurrencyPowerConvertor<Currency, Power> {
> 	fn to_currency(power: Power, pool: Currency) -> Currency;
> 
> 	fn to_power(currency: Currency, pool: Currency) -> Power;
> }
> ```
> 
> ```rust
> // runtime impl.rs
> use crate::TOTAL_POWER;
> use node_primitives::{Balance, Power};
> 
> pub struct CurrencyPowerHandler;
> 
> impl<Currency> CurrencyPowerConvertor<Currency, Power> for CurrencyPowerHandler 
> where
> 	Currency: Bounded + SimpleArithmetic + TryInto<Balance> + TryFrom<Balance>,
> {
> 	fn to_currency(power: Power, pool: Currency) -> Currency {
> 		Currency::saturated_from(
> 			Perquintill::from_rational_approximation(
> 				power,
> 				TOTAL_POWER / 2,
> 			) * pool.saturated_into::<Balance>().max(1)
> 		)
> 	}
> 	
> 	fn to_power(currency: Currency, pool: Currency) -> Power {
> 		Perquintill::from_rational_approximation(
> 			currency.saturated_into::<Balance>(),
> 			pool.saturated_into::<Balance>().max(1),
> 		) * (TOTAL_POWER / 2)
> 	}
> }
> ```
> 
> `Pool` is required to calculate `Power`, can not `impl Convert`, we have to modify the phragmen module.

This design makes sense.

**Comment by AurevoirXavier** [comment]
deps on #262
