### ISSUE TITLE
Sync Stalls

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#251]
The same as:

https://github.com/paritytech/substrate/issues/4367
https://github.com/paritytech/substrate/issues/4398

**Comment by AurevoirXavier** [comment]
Might be fixed in #218

**Comment by AurevoirXavier** [comment]
Have to specify `--no-grandpa` to keep syncing.

**Comment by AurevoirXavier** [comment]
fixed in #268

**Comment by HackFisher** [comment]
Found in latest devnet
