### ISSUE TITLE
Kton的reward_paid_out 重复计算问题

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia#27]
持有kton的奖励会被重复计入：
<img width="680" alt="屏幕快照 2019-07-03 下午12 41 30" src="https://user-images.githubusercontent.com/1608576/60563903-31ed5680-9d90-11e9-9082-075cf7c3324c.png">
这里的balance是用户持有的所有kton，但是update_reward_paid_out方法又是一个增量方法，那么每次调用这个方法的时候，kton都会被全量计算一遍奖励，重复计入reward_paid_out。

**Comment by hammeWang** [comment]
@wuminzhe `update_reward_paid_out`只会更新每个人已经领取的reward数量，而`make_free_balance_be`是变动kton余额。在更新kton余额时，会自动更新用户当前的已领取reward数量。
前者是针对ring的计算，后者是对kton的计算。

**Comment by wuminzhe** [comment]
假设reward per share是1，某个用户reward_paid_out初始为0

这个用户deposit ring后得到了100个kton，那么reward_paid_out就是100；
然后这个用户继续depost，又得到了100个kton，那么reward_paid_out应该是200，但是按照代码逻辑，这个值是300

**Comment by wuminzhe** [comment]
看了[https://github.com/darwinia-network/rfcs/issues/6](url)里的p3d算法，有点解惑，不过还有有疑问，按照p3d:

    My_ETH_Dividends_Balance_Claimed[address] += {Total_ETH_Dividends_Balance - Last_Claim_Total_ETH_Dividends_Balance[address]} * [balance_before/balance_total_before]

换个形式就是：

    My_ETH_Dividends_Balance_Claimed[address] +=  balance_before * [{Total_ETH_Dividends_Balance - Last_Claim_Total_ETH_Dividends_Balance[address]}/balance_total_before]

等价到darwinia里的，就是:

   reward_paid_out += kton balance * reward per share增量

但是代码里似乎用的不是增量：

![屏幕快照 2019-07-03 下午3 48 06](https://user-images.githubusercontent.com/1608576/60573386-26a72480-9daa-11e9-8476-745b3acbda4a.png)
