### ISSUE TITLE
RewardPaidOut疑似有双重意义

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia#28]
第一重：记录用户持有kton的奖励  

    用户获得了kton后，系统根据这些新的kton奖励用户ring，但是只是记下账，记在reward_paid_out，这个时候并没有将奖励实际打到用户账户

第二重：

    用户claim reward时，用于记录 实际打币数量

这两者似有冲突，其中之一的逻辑是错误的。

**Comment by HackFisher** [comment]
The old design of staking system has been deprecated, close this.
