### ISSUE TITLE
TODO: Treasury support Kton Proposal

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#285]

**Comment by HackFisher** [comment]
Slash in staking module may collect some kton to treasury (or directly burned)?

If treasury requires to manage KTON, then we should support KTON in treasury too.

We can define RingProposal/Kton Proposal, or define enum value such as RingOrKtonBalance?

**Comment by AurevoirXavier** [comment]
Slashed *Kton* goes to treasury.

**Comment by HackFisher** [comment]
> Slashed _Kton_ goes to treasury.

Ok, then we should support proposals to spend KTON. (burn KTON is also spending it in some way)

**Comment by clearloop** [comment]
Hi folks, I'll join this issue till it gets solved next days~ Just got some work about [GenePaper][1], logic and confusion of my mind occur as below.

### Where KTON from? 

KTON can **only obtained by locking RING**.

+ POS -> RING
  + States
    + Staking-lock -> KTON

### How to spend KTON?

1. Transfer to other accounts
  a. ...
2. burned by slashing

### Balances supports(in file structures)

+ `bin/node/runtime`
+ `frame/chainrelay/eth/backing`
+ `frame/stacking`
+ `frame/treasury`

## Abstract working steps

+ Add READMEs to `frame/balances`  
+ Complete tests according to `RING` and `Treasury Traits`
+ Review the reflecting from KTON to `treasury` and `?balances`

For `treasury` and `balances`, I'm not sure about the relationship inside them, so, **if `treasury` is the concept in substrate projects, and `balances` is the way we talking about `treasury` in the product?**


[1]: https://evolution.l2me.com/darwinia/Darwinia_Genepaper_EN.pdf

**Comment by clearloop** [comment]
## Convert Balance

Darwinia has `KTON` and `RING`, both of them original by `Currency<Self::AccountId> + ReservableCurrency<Self::AccountId>`, it might be an hack embedding them into one Generic Trait.

For example: 

```rust
pub struct Module<T: Trait> for enum Call where origin: T::Origin { 
    const ProposalBondMinimum: RingBalance<T> = T::ProposalBondMinimum::get();
    // ...
}
```
Constant `ProposalBondMinimum` require a specific `type`, it will be a mess using `enum`, because `Module` can be called by outside crates, once we change this to `enum`, it will be a lot of work.

### Solution

What about implementing `std::convert` for `KTON` and `RING`, this will cause less change **but** easy to be mixed up in some way.

> Furthermore, if implementing `std::convert`, will it be better composing a new type named `DarwiniaCurrency`? 

However, since `RING` is the base currency, I think just use `RING` might be a gentle way.

**Comment by clearloop** [comment]
> [#5081][#5081]

Substrate doesn't support **multiple currencies** in `pallet_treasry` currently XD, we might need to discuss out **a more flexible way** to implement both `KTON` and `RING` in `darwinia`.

### Possible solution(Temporarily)

1. Just use the original `Currency`(or `RingCurrency`) as `Currency` in `darwinia_treasury`, 
2. Declares `RingBalance` and `KtonBalance` equals to Orignal `Balance`, ports them out supporting other modules to keep moving.
3. Finish tests with some expandable spaces.


[#5081]: https://github.com/paritytech/substrate/issues/5081

**Comment by HackFisher** [comment]
> > [#5081](https://github.com/paritytech/substrate/issues/5081)
> 
> Substrate might not support **multiple currencies** in `pallet_treasry` currently XD, we might need to discuss out **a more flexible way** to implement both `KTON` and `RING` in `darwinia`.
> 
> ### Possible solution(Temporarily)
> 1. Just use the original `Currency`(or `RingCurrency`) as `Currency` in `darwinia_treasury`,
> 2. Declares `RingBalance` and `KtonBalance` equals to Orignal `Balance`, ports them out supporting other modules to keep moving.
> 3. Finish tests with some expandable spaces.
> 
> ### Or
> 1. A standalone layer filtering our currencies.
> 2. PR substrate to reach this.

Similar cases of ```RingBalance | KtonBalance``` in staking could be taken as a reference:

https://github.com/darwinia-network/darwinia/blob/develop/frame/staking/src/lib.rs#L395

Or, impelementing in seprate Call and storage for RING and KTON is also viable.

**Comment by clearloop** [comment]
> I prefer to use enum over trait.

Cooool! It works!!! I have no idea that rust can write like this before!

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/darwinia/pull/306
