### ISSUE TITLE
Review: Check Overflow and Underflow

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#315]
Follow the guide here:
https://github.com/darwinia-network/darwinia/wiki/Best-Practice-for-Darwinia-Security-Review#overflow_checking

Especially the slash parts.

**Comment by HackFisher** [comment]
Remember to pick and merge this pr:
https://github.com/paritytech/substrate/pull/4281

**Comment by AurevoirXavier** [comment]
## Plan to review the module:

### darwinia module
- [ ] **2020/3/13 eth-relay**
- [ ] **2020/3/13 eth-relay**
- [ ] **2020/3/13 eth-relay**
- [ ] **2020/3/13 eth-relay**
- [ ] **2020/3/13 eth-relay**

**Comment by clearloop** [comment]
I would like to pick:

+ [ ] balances
+ [ ] darwinia-staking
+ [ ] treasury

because I'm more familiar with these modules than others, and also have a doc plan for them.

**Comment by AurevoirXavier** [comment]
> I would like to pick:
> 
> * [ ]  balances
> * [ ]  darwinia-staking
> * [ ]  treasury
> 
> because I'm more familiar with these modules than others, and also have a doc plan for them.

I think we need a meeting. Every module you should participate in. Please prepare a day advance.

**Comment by clearloop** [comment]
> I think we need a meeting. Every module you should participate in. Please prepare a day advance.

Well, deal...btw, would you mind to check the #331 later, I need to update my local branch now.

**Comment by AurevoirXavier** [comment]
Move to #353.
