### ISSUE TITLE
Review: Account's References

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#317]
Due to [**Lazy Reaping**](https://github.com/paritytech/substrate/pull/4895).

**Comment by HackFisher** [comment]
https://github.com/paritytech/substrate/blob/9c59bcdb21/frame/contracts/src/lib.rs#L948

https://github.com/paritytech/substrate/blob/9c59bcdb21b3e71759f2e4a02911250224805362/frame/contracts/src/tests.rs#L120


BTW, we should document a best practice for these security checkings.

**Comment by AurevoirXavier** [comment]
Maybe we can use OnKilledAccount to collect the locks.

**Comment by AurevoirXavier** [comment]
Move to #353.
