### ISSUE TITLE
Check Unbonding Value

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#318]

**Comment by AurevoirXavier** [comment]
https://github.com/darwinia-network/darwinia/blob/develop/frame/staking/src/lib.rs#L1137

`extra` should be `stash_balance - active_ring - unbonding_ring`

**Comment by HackFisher** [comment]
Should use usable_balance instead of free_balance.

**Comment by AurevoirXavier** [comment]
usable_balance is a module call
consider move it to lockablecurrency
and the frozens are calculated from lock put it into lockablecurrency would be better
