### ISSUE TITLE
Keep test case and ci updated when developing

### ISSUE THREAD

**Issue by yanganto** [darwinia-network/darwinia#325]
The test and ci are also parts of the development.
There is no KTON test case in the current `develop` branch and the Staking test case is reverted.
- The `.maintain/ci/darwinia_test_script.sh` should be updated with #307 merged.
- The staking test case should be kept in passed without comment when #312 merged, this also revert the work of #293.

**Comment by clearloop** [comment]
Well, I'm trying to fix `treasury`'s tests now.

**Comment by AurevoirXavier** [comment]
We don’t need the KTON tests. Those two module use the same code.

**Comment by clearloop** [comment]
> We don’t need the KTON tests. Those two modules use the same code.

I realized it this afternoon, I'll keep some functional tests with KTON parallel in treasury's tests, and delete most of them.
