### ISSUE TITLE
节点地址与session key绑定丢失

### ISSUE THREAD

**Issue by hging** [darwinia-network/darwinia#34]
第一开始部署时候 账号`5FFRMCGBkuBv4S31nVJZ6HatHe3egNh6qhVwCCt6BGCTN3xy`绑定了一个session-key为`5DMCtHLA6kQdbThbrg7ofREDtmFseDXfbCZuPn8tAAqBP491`
在某时间，关联丢失，导致无法出块，查验后账号绑定的session-key变空
尝试再次绑定这个session-key，均失败
重新生成一个session-key 即可绑定成功，新的session-key为`5GiQ6KVeCZCRwwLK8QyrPvyqtw6BPzBLwiujRrfVk17U7d8B`

问题出现流程：
将controller账号的余额全部转出，session-key绑定即丢失。

**Comment by hammeWang** [comment]
地址上的ring不能全部转出哦~
全网有个最低账户余额要求，暂定为1.
所以保证地址上有最少为1的ring哦

**Comment by hammeWang** [comment]
issue closed.
