### ISSUE TITLE
Support and include MMR in blockheader

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#344]
For easier darwinia relay support

**Comment by AurevoirXavier** [comment]
Transfer to https://github.com/darwinia-network/research?

**Comment by HackFisher** [comment]
> Transfer to https://github.com/darwinia-network/research?

Actually the research is almost done? The works left is about the engineering stuffs related to Substrate Runtime primitives, constructing block and MMR calculating.

Here are some code links:

Header Struct:
https://github.com/paritytech/substrate/blob/v2.0.0-alpha.3/primitives/runtime/src/generic/header.rs#L39

Block Builder:
https://github.com/paritytech/substrate/blob/v2.0.0-alpha.3/client/block-builder/src/lib.rs#L205

MMR struct and append:

https://github.com/darwinia-network/darwinia/blob/icefrog/core/merkle-mountain-range/src/mmr.rs#L44

It will be great if we can do it in Crab Network.

**Comment by HackFisher** [comment]
We could implement it in a separate branch while waiting for the substrate stable release.

**Comment by HackFisher** [comment]
There is a ```digest``` data in ```Header``` struct, could we make use of it for easy extend of Substrate code, if it works, then we might not need to introduce modification to Substrate runtime primitives too much.

https://github.com/paritytech/substrate/blob/v2.0.0-alpha.3/primitives/runtime/src/generic/header.rs#L52

```
pub struct Header<Number: Copy + Into<U256> + TryFrom<U256>, Hash: HashT> {
	/// The parent hash.
	pub parent_hash: Hash::Output,
	/// The block number.
	#[cfg_attr(feature = "std", serde(
		serialize_with = "serialize_number",
		deserialize_with = "deserialize_number"))]
	pub number: Number,
	/// The state trie merkle root
	pub state_root: Hash::Output,
	/// The merkle root of the extrinsics.
	pub extrinsics_root: Hash::Output,
	/// A chain-specific digest of data useful for light clients or referencing auxiliary data.
	pub digest: Digest<Hash::Output>,
}
```
