### ISSUE TITLE
Remove Some Modules in Next Substrate Release

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#347]
To keep the same deps version, I've to modify the session module in https://github.com/darwinia-network/darwinia/pull/346.

**Comment by AurevoirXavier** [comment]
### To keep all deps using the same version of session, I modify these module:
- **frame/**
- **frame/**
- **frame/**
- **frame/**
- **frame/**
- **frame/**

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/darwinia/pull/356
