### ISSUE TITLE
Are there compatible issues when upgrading runtime have changed Storage name or structure?

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#35]
Shouldn't there be a migration design just like db migration?

**Comment by AurevoirXavier** [comment]
Could you explain it in more detail? So we can build a testing env for this.

**Comment by hammeWang** [comment]
I guess, for now, we could just do it in a 'smart-contract-upgrade' way.

**Comment by HackFisher** [comment]
> Could you explain it in more detail? So we can build a testing env for this.

For example, In Balances Module:

The current ReserveBalance is as following:
```
pub ReservedBalance get(fn reserved_balance): map T::AccountId => T::Balance;
```

What is we change the name of ```ReservedBalance``` to ```ReservedX```, or change the type of ```map``` to ```vec``` etc. The underline storage keys might be changed or broken then.

I guess we may meet such migration challenges in future mainet upgrading process, and asking for the best practice.

In worst case, we could do migration through Extrinsics, just like Ethereum TXs?

**Comment by HackFisher** [comment]
Migrate example:

https://github.com/paritytech/substrate/blob/master/frame/staking/src/migration.rs

**Comment by AurevoirXavier** [comment]
#218
