### ISSUE TITLE
Make the source of the Ethereum offchain worker redundant

### ISSUE THREAD

**Issue by yanganto** [darwinia-network/darwinia#371]
The source to observe Ethereum should be redundant and more configurable.

Please check the conversation in https://github.com/darwinia-network/darwinia/pull/335/files#diff-1564a4df147ace619ae3e556faf2ff58R180
```
This worker gets the block info now relies on Ethscan's API, so it already wraps a web service.

I think the way to avoid parsing a string into bytes is to use more low-level client, and there is still no grpc/socket client API in the off-chain worker. So I think parsing is not avoidable.

By the way, the response format of Ethscan is a JSON with sorted fields, and also is the same as the Ethereum gateway of Cloudflare. And the worker is easily integrated with multiple sources and will be implemented later to enhance the robust.
```

This issue may better be fixed after #370 and #26.

**Comment by HackFisher** [comment]
Duplicated with #53 and https://github.com/darwinia-network/darwinia.js/issues/5

Substrate offchain worker doesn't have to be redundant, but it's companion service should.

Substrate offchain worker should focus on define the task requirements and spec, companion service will handle stability and flexibilit, incentive model ensures redundant and competitive market  #303
