### ISSUE TITLE
Add RPC methods' document for every pallets

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/darwinia#377]
## Why?

This is friendly for developers who want to contribute to Darwinia, including our developers who don't write rust.

I'm wondering how to call Darwinia's RPC for a long time, though I can wite little rust to Darwinia, this is very important for new Darwinia developers to understand Darwinia because blockchain is different from common software in some way...

And this can help us consider more about launching instead of all in engineering.

## How?

The implementation is quite easy, all methods in substrate `decl_xxxx!` macro will generate RPC interfaces automatically, I bet most developers can understand the structure and read the source code of Darwinia gently even they haven't written rust before, of course, if they know these.

### Storage and Extrinsic
|  macro                           |  usage                                               |
|-----------------------|----------------------------------|
| `decl_storage!`      | api.query.\<module\>.\<method\>    |
| `decl_module!`       | api.tx.\<module\>.\<method\>         |

### Constants
|   trait                              |   usage                                               |
|-----------------------|----------------------------------|
| `frame_system::Trait` | api.consts.\<module\>.\<method\> |

### Default
| default                        |  usage                                               |
|---------------------|----------------------------------|
| substrate default     | api.rpc.\<module\>.\<method\>  |

**Comment by AurevoirXavier** [comment]
Already in subscan's plan. Assign to @yakio.
