### ISSUE TITLE
How to improve the compile time of darwinia?

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/darwinia#402]
## Spec

For example, every time I update my local branch from the official remote, I will take a nap, lying on my bed and waiting for the compilation...and sometimes I just fall into sleep.

The `sccache` is blocked by some substrate deps, I don't know if there is any other way to improve the compile times.

> Note: The directly way to watch the complie time is adding `RUSTFLAGS='-Z time-passes'` before our `cargo buiid`.

## Refs

+ [How to improve Rust compile times by whole lot.. easily?][0]
+ [How to speed up the Rust compiler some more in 2019?][1]
+ [Where Rustc Spends Its Time?][2]
+ [Outputs of the build script][3]
+ [Compile times][4]

[0]: https://users.rust-lang.org/t/how-to-improve-rust-compile-times-by-whole-lot-easily/38134/8
[1]: https://blog.mozilla.org/nnethercote/2019/10/11/how-to-speed-up-the-rust-compiler-some-more-in-2019/
[2]: https://wiki.alopex.li/WhereRustcSpendsItsTime?revision=78ab2254b4113501fee574867730c1dc219639df
[3]: https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script
[4]: https://www.reddit.com/r/rust/comments/aqy7ns/compile_times/

**Comment by AurevoirXavier** [comment]
Only the first time you need to compile all the crates. (I remove the unused deps as possible as I can)

For the rest parts, it's rust problem not darwinia.

---

So currently, buy you a new CPU.

**Comment by clearloop** [comment]
My computer is dying...there must be some way to improve this.

### For darwinia part

Watch out the `deps` might be the main way, for example, I used to depend on `pyo3` in one of my projects and it really burns the compile times, though it is not the main feature of that project.

Here is a tool I'd like to try later: [cargo-sweep][0].

### For rust part

After a quick view about the refs I listed above, they are a lot of discussions about `global cache`, I'm wondering if there is some global cache solution that can support `substrate-deps`.

[0]: https://github.com/holmgr/cargo-sweep
