### ISSUE TITLE
Proposals for kton module code refactoring

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia#43]
After understanding the kton module code, I think it involves too many responsibilities and can be separated more clearly: 

1. move lock rings logic to balances module, and then
2. increase kton balance in kton module through rings locked event.
3. move reward logic to a separate module maybe named "rewarding". (dividend-sharing logic here)
4. after kton balance changed, notify rewarding module to do reward.
5. SystemCurrency trait? I think this is not a general behavior.

**Comment by wuminzhe** [comment]
kton's `deposit_creating` function should change name to `deposit_into_existing` according to `Currency` trait definition.

**Comment by HackFisher** [comment]
Deprecated design, refer staking design in latest genepaper:

https://github.com/darwinia-network/rfcs/blob/master/paper/Darwinia_Genepaper_EN.pdf
