### ISSUE TITLE
Compile failed on CentOS-7.7

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/darwinia#435]
## CentOS 7.7

```
$ uname -a

Linux VM_0_14_centos 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

<details>
  <summary>Compile logs</summary>
  <pre><code>
[dev@VM_0_14_centos darwinia]$ cargo build
   Compiling crab-runtime v0.5.4 (/home/dev/darwinia/runtime/crab)
   Compiling darwinia-cli v0.5.4 (/home/dev/darwinia/cli)
   Compiling jobserver v0.1.21
   Compiling getrandom v0.1.14
   Compiling num_cpus v1.13.0
   Compiling parking_lot_core v0.7.2
   Compiling which v3.1.1
   Compiling iovec v0.1.4
   Compiling net2 v0.2.33
   Compiling atty v0.2.14
   Compiling async-task v1.3.1
   Compiling get_if_addrs v0.5.3
   Compiling time v0.1.43
   Compiling dirs-sys v0.3.4
   Compiling signal-hook-registry v1.2.0
   Compiling errno v0.2.5
   Compiling rand_os v0.1.3
   Compiling rand v0.5.6
   Compiling fs-swap v0.2.4
   Compiling memmap v0.7.0
   Compiling rand v0.4.6
   Compiling rpassword v4.0.5
   Compiling fdlimit v0.1.4
   Compiling quote v1.0.3
   Compiling indexmap v1.3.2
   Compiling crossbeam-utils v0.7.2
   Compiling memoffset v0.5.4
   Compiling hashbrown v0.7.2
   Compiling kv-log-macro v1.0.4
   Compiling want v0.3.0
   Compiling want v0.2.0
   Compiling dns-parser v0.8.0
   Compiling aho-corasick v0.7.10
   Compiling bstr v0.2.12
   Compiling generic-array v0.12.3
   Compiling parking_lot_core v0.6.2
   Compiling parking_lot v0.9.0
   Compiling snow v0.6.2
   Compiling hyper v0.12.35
   Compiling smallvec v0.6.13
   Compiling uint v0.8.3
   Compiling tiny-keccak v2.0.2
   Compiling hash256-std-hasher v0.15.2
   Compiling uint v0.8.2 (https://github.com/darwinia-network/parity-common.git#12a86aa8)
   Compiling tiny-keccak v1.5.0
   Compiling num-traits v0.2.11
   Compiling blake2-rfc v0.2.18
   Compiling rand_chacha v0.1.1
   Compiling rand_pcg v0.1.2
   Compiling url v2.1.1
   Compiling url v1.7.2
   Compiling libflate v0.1.27
   Compiling bindgen v0.53.2
   Compiling region v2.1.2
   Compiling nix v0.17.0
   Compiling nom v5.1.1
   Compiling unicase v2.6.0
   Compiling tokio-sync v0.2.0-alpha.6
   Compiling cc v1.0.52
   Compiling rand_core v0.5.1
   Compiling const-random-macro v0.1.8
   Compiling futures-cpupool v0.1.8
   Compiling threadpool v1.8.0
   Compiling parking_lot v0.10.2
   Compiling prost-build v0.6.1
   Compiling bytes v0.4.12
   Compiling mio v0.6.21
   Compiling clap v2.33.0
   Compiling directories v2.0.2
   Compiling statrs v0.10.0
   Compiling rand v0.3.23
   Compiling syn v1.0.18
   Compiling petgraph v0.5.0
   Compiling gimli v0.20.0
   Compiling crossbeam-queue v0.2.1
   Compiling crossbeam-channel v0.4.2
   Compiling tokio-executor v0.1.10
   Compiling crossbeam-epoch v0.8.2
   Compiling regex v1.3.7
   Compiling digest v0.8.1
   Compiling block-buffer v0.7.3
   Compiling crypto-mac v0.7.0
   Compiling block-cipher-trait v0.6.2
   Compiling stream-cipher v0.3.2
   Compiling num-integer v0.1.42
   Compiling num-complex v0.2.4
   Compiling approx v0.3.2
   Compiling rand v0.6.5
   Compiling cexpr v0.4.0
   Compiling tokio-executor v0.2.0-alpha.6
   Compiling clear_on_drop v0.2.3
   Compiling backtrace-sys v0.1.36
   Compiling jemalloc-sys v0.3.2
   Compiling ring v0.16.12
   Compiling ring v0.16.12
   Compiling libz-sys v1.0.25
   Compiling zstd-sys v1.4.15+zstd.1.4.4
   Compiling raw-cpuid v7.0.3
   Compiling substrate-wasmtime-runtime v0.13.0-threadsafe.1
   Compiling libloading v0.5.2
   Compiling rand_pcg v0.2.1
   Compiling rand_chacha v0.2.2
   Compiling const-random v0.1.8
   Compiling parity-db v0.1.2
   Compiling tokio-io v0.1.13
   Compiling http v0.1.21
   Compiling string v0.2.1
   Compiling tokio-buf v0.1.1
   Compiling mio-uds v0.6.7
   Compiling mio-extras v2.0.6
   Compiling names v0.11.0
   Compiling synstructure v0.12.3
   Compiling wasm-bindgen-backend v0.2.60
   Compiling syn-mid v0.5.0
   Compiling serde_derive v1.0.106
   Compiling futures-macro v0.3.4
   Compiling impl-trait-for-tuples v0.1.3
   Compiling sp-debug-derive v2.0.0-dev (https://github.com/darwinia-network/substrate.git?tag=v2.0.0-alpha.darwinia.6#05275e80)
   Compiling ref-cast-impl v1.0.1
   Compiling tracing-attributes v0.1.7
   Compiling derive_more v0.99.5
   Compiling paste-impl v0.1.11
   Compiling thiserror-impl v1.0.16
   Compiling prost-derive v0.6.1
   Compiling pin-project-internal v0.4.9
   Compiling asn1_der_derive v0.1.2
   Compiling frame-support-procedural-tools-derive v2.0.0-dev (https://github.com/darwinia-network/substrate.git?tag=v2.0.0-alpha.darwinia.6#05275e80)
   Compiling libp2p-core-derive v0.18.0
   Compiling scroll_derive v0.10.1
   Compiling strum_macros v0.16.0
   Compiling slog_derive v0.2.0
   Compiling rlp-derive v0.1.0 (https://github.com/darwinia-network/parity-common.git#12a86aa8)
   Compiling enumflags2_derive v0.6.4
   Compiling tokio-timer v0.2.13
   Compiling tokio-current-thread v0.1.7
   Compiling crossbeam-deque v0.7.3
   Compiling Inflector v0.11.4
   Compiling env_logger v0.6.2
   Compiling env_logger v0.7.1
   Compiling globset v0.4.5
   Compiling sha2 v0.8.1
   Compiling sha3 v0.8.2
   Compiling sha-1 v0.8.2
   Compiling hmac v0.7.1
   Compiling pbkdf2 v0.3.0
   Compiling blake2 v0.8.1
   Compiling aes-soft v0.3.3
   Compiling twofish v0.2.0
   Compiling ctr v0.3.2
   Compiling num-bigint v0.2.6
   Compiling chrono v0.4.11
   Compiling alga v0.9.3
error: failed to run custom build command for `substrate-wasmtime-runtime v0.13.0-threadsafe.1`

Caused by:
  process didn't exit successfully: `/home/dev/darwinia/target/debug/build/substrate-wasmtime-runtime-b98fd94f3f45f98a/build-script-build` (exit code: 1)
--- stdout
cargo:rerun-if-changed=signalhandlers/SignalHandlers.cpp
cargo:rerun-if-changed=signalhandlers/SignalHandlers.hpp
cargo:rerun-if-changed=signalhandlers/Trampolines.cpp
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,mmx,sse,sse2")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-std=c++11" "-fno-exceptions" "-fno-rtti" "-o" "/home/dev/darwinia/target/debug/build/substrate-wasmti
me-runtime-abf6e762b0aa42ed/out/signalhandlers/SignalHandlers.o" "-c" "signalhandlers/SignalHandlers.cpp"
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-std=c++11" "-fno-exceptions" "-fno-rtti" "-o" "/home/dev/darwinia/target/debug/build/substrate-wasmti
me-runtime-abf6e762b0aa42ed/out/signalhandlers/Trampolines.o" "-c" "signalhandlers/Trampolines.cpp"

--- stderr

error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-std=c++11" "-fno-exceptions" "-fno-rtti" "-o" "/home/dev/darwinia/target/debug/build/s
ubstrate-wasmtime-runtime-abf6e762b0aa42ed/out/signalhandlers/SignalHandlers.o" "-c" "signalhandlers/SignalHandlers.cpp" with args "c++" failed to start.

warning: build failed, waiting for other jobs to finish...
error: build failed
 </code></pre>
</details>

**Comment by AurevoirXavier** [comment]
```
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
CRATE_CC_NO_DEFAULTS = None
```

You don't have cpp toolchains.

**Comment by clearloop** [comment]
After installing `clang` and `c++`, still can not compile, seems caused by `rocksdb`

```
yum install gcc-c++ clang
```
<details>
<summary>Build logs</summary>
<pre><code>
[dev@VM_0_14_centos darwinia]$ cargo build --release                                                                                                                                                              
   Compiling librocksdb-sys v6.7.4
   Compiling rocksdb v0.13.0
   Compiling kvdb-rocksdb v0.7.0
   Compiling sc-client-db v0.8.0-dev (https://github.com/darwinia-network/substrate.git?tag=v2.0.0-alpha.darwinia.6#05275e80)
   Compiling sc-service v0.8.0-dev (https://github.com/darwinia-network/substrate.git?tag=v2.0.0-alpha.darwinia.6#05275e80)
   Compiling sc-informant v0.8.0-dev (https://github.com/darwinia-network/substrate.git?tag=v2.0.0-alpha.darwinia.6#05275e80)
   Compiling darwinia-service v0.5.4 (/home/dev/darwinia/service)
error: could not compile `darwinia-service`.

Caused by:
  process didn't exit successfully: `rustc --crate-name darwinia_service --edition=2018 service/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="db"' --cfg 'feature="default"' --cfg 'feature="full-node"' -C metadata=61b4c59a0b86bb56 -C extra-filename=-61b4c59a0b86bb56 --out-dir /home/dev/darwinia/target/release/deps -L dependency=/home/dev/darwinia/target/release/deps --extern crab_runtime=/home/dev/darwinia/target/release/deps/libcrab_runtime-0784109843a620fd.rmeta --extern darwinia_balances_rpc_runtime_api=/home/dev/darwinia/target/release/deps/libdarwinia_balances_rpc_runtime_api-29e9aee7500c8adb.rmeta --extern darwinia_primitives=/home/dev/darwinia/target/release/deps/libdarwinia_primitives-e4b4cc0f0e4055c9.rmeta --extern darwinia_rpc=/home/dev/darwinia/target/release/deps/libdarwinia_rpc-f5f21ff7052ff0a0.rmeta --extern darwinia_support=/home/dev/darwinia/target/release/deps/libdarwinia_support-788a2b73122dfd84.rmeta --extern frame_system_rpc_runtime_api=/home/dev/darwinia/target/release/deps/libframe_system_rpc_runtime_api-a7da121405d68176.rmeta --extern futures=/home/dev/darwinia/target/release/deps/libfutures-70a2c8f17446a59a.rmeta --extern log=/home/dev/darwinia/target/release/deps/liblog-d564efa95c4b564c.rmeta --extern pallet_im_online=/home/dev/darwinia/target/release/deps/libpallet_im_online-df364ea95520e7cc.rmeta --extern pallet_transaction_payment_rpc_runtime_api=/home/dev/darwinia/target/release/deps/libpallet_transaction_payment_rpc_runtime_api-c3dbe437f154531c.rmeta --extern codec=/home/dev/darwinia/target/release/deps/libparity_scale_codec-c527daf84968a121.rmeta --extern sc_authority_discovery=/home/dev/darwinia/target/release/deps/libsc_authority_discovery-cf8ff8b08b003b61.rmeta --extern sc_basic_authorship=/home/dev/darwinia/target/release/deps/libsc_basic_authorship-98d32fadc09e7cd7.rmeta --extern sc_chain_spec=/home/dev/darwinia/target/release/deps/libsc_chain_spec-e9ff5abe0762873d.rmeta --extern sc_client=/home/dev/darwinia/target/release/deps/libsc_client-6dfa83fd10d810c3.rmeta --extern sc_client_api=/home/dev/darwinia/target/release/deps/libsc_client_api-109aa8bc65d48228.rmeta --extern sc_client_db=/home/dev/darwinia/target/release/deps/libsc_client_db-29d0d9e34ab8f83c.rmeta --extern sc_consensus_babe=/home/dev/darwinia/target/release/deps/libsc_consensus_babe-7c09230ca4441974.rmeta --extern sc_executor=/home/dev/darwinia/target/release/deps/libsc_executor-84772efadeaf96d8.rmeta --extern sc_finality_grandpa=/home/dev/darwinia/target/release/deps/libsc_finality_grandpa-cea27eaed013f79b.rmeta --extern sc_network=/home/dev/darwinia/target/release/deps/libsc_network-7e0dd83fb537567b.rmeta --extern sc_service=/home/dev/darwinia/target/release/deps/libsc_service-c364184907cbaa16.rmeta --extern sc_telemetry=/home/dev/darwinia/target/release/deps/libsc_telemetry-a7e2c60311e3916c.rmeta --extern sc_transaction_pool=/home/dev/darwinia/target/release/deps/libsc_transaction_pool-06888daa5c6b740b.rmeta --extern serde=/home/dev/darwinia/target/release/deps/libserde-74e941e6879601ec.rmeta --extern serde_json=/home/dev/darwinia/target/release/deps/libserde_json-6d036f6df78aaae3.rmeta --extern sp_api=/home/dev/darwinia/target/release/deps/libsp_api-8d05f6ec162698b3.rmeta --extern sp_authority_discovery=/home/dev/darwinia/target/release/deps/libsp_authority_discovery-03418a4adfb040f9.rmeta --extern sp_block_builder=/home/dev/darwinia/target/release/deps/libsp_block_builder-0b5feff9bad998d5.rmeta --extern sp_blockchain=/home/dev/darwinia/target/release/deps/libsp_blockchain-08113766611ea1f7.rmeta --extern sp_consensus=/home/dev/darwinia/target/release/deps/libsp_consensus-2c259d378414d378.rmeta --extern sp_consensus_babe=/home/dev/darwinia/target/release/deps/libsp_consensus_babe-3e4172f92ecb4687.rmeta --extern sp_core=/home/dev/darwinia/target/release/deps/libsp_core-7f80c847f49694a2.rmeta --extern sp_inherents=/home/dev/darwinia/target/release/deps/libsp_inherents-194512131a3c3b13.rmeta --extern sp_offchain=/home/dev/darwinia/target/release/deps/libsp_offchain-3031b7fa5bbd732a.rmeta --extern sp_runtime=/home/dev/darwinia/target/release/deps/libsp_runtime-fd97923c3b45dc6d.rmeta --extern sp_session=/home/dev/darwinia/target/release/deps/libsp_session-fa9caaf783976604.rmeta --extern sp_transaction_pool=/home/dev/darwinia/target/release/deps/libsp_transaction_pool-f0235bd93a3c92c4.rmeta --extern substrate_prometheus_endpoint=/home/dev/darwinia/target/release/deps/libsubstrate_prometheus_endpoint-683afdc9e7c02485.rmeta -L native=/home/dev/darwinia/target/release/build/clear_on_drop-8b68bc7a28c0b6f9/out -L native=/home/dev/darwinia/target/release/build/jemalloc-sys-2f2a4e887bba4371/out/build/lib -L native=/home/dev/darwinia/target/release/build/backtrace-sys-6aaafca51d55a11e/out -L native=/home/dev/darwinia/target/release/build/ring-504546fc4340c37d/out -L native=/home/dev/darwinia/target/release/build/libz-sys-ff199467329df948/out/build -L native=/home/dev/darwinia/target/release/build/substrate-wasmtime-runtime-44d8c50330b5ec50/out -L native=/home/dev/darwinia/target/release/build/zstd-sys-f023f25a19f042fe/out -L native=/home/dev/darwinia/target/release/build/librocksdb-sys-65d4b1beaa416bf4/out -L native=/home/dev/darwinia/target/release/build/librocksdb-sys-65d4b1beaa416bf4/out` (signal: 9, SIGKILL: kill)
</code></pre>
</details>

**Comment by AurevoirXavier** [comment]
> After installing `clang` and `c++`, still can not compile, seems caused by `rocksdb`
> 
> ```
> yum install gcc-c++ clang
> ```
> <details>
> <summary>Build logs</summary>
> <pre><code>
> [dev@VM_0_14_centos darwinia]$ cargo build --release                                                                                                                                                              
>    Compiling librocksdb-sys v6.7.4
>    Compiling rocksdb v0.13.0
>    Compiling kvdb-rocksdb v0.7.0
>    Compiling sc-client-db v0.8.0-dev (https://github.com/darwinia-network/substrate.git?tag=v2.0.0-alpha.darwinia.6#05275e80)
>    Compiling sc-service v0.8.0-dev (https://github.com/darwinia-network/substrate.git?tag=v2.0.0-alpha.darwinia.6#05275e80)
>    Compiling sc-informant v0.8.0-dev (https://github.com/darwinia-network/substrate.git?tag=v2.0.0-alpha.darwinia.6#05275e80)
>    Compiling darwinia-service v0.5.4 (/home/dev/darwinia/service)
> error: could not compile `darwinia-service`.
> 
> Caused by:
>   process didn't exit successfully: `rustc --crate-name darwinia_service --edition=2018 service/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="db"' --cfg 'feature="default"' --cfg 'feature="full-node"' -C metadata=61b4c59a0b86bb56 -C extra-filename=-61b4c59a0b86bb56 --out-dir /home/dev/darwinia/target/release/deps -L dependency=/home/dev/darwinia/target/release/deps --extern crab_runtime=/home/dev/darwinia/target/release/deps/libcrab_runtime-0784109843a620fd.rmeta --extern darwinia_balances_rpc_runtime_api=/home/dev/darwinia/target/release/deps/libdarwinia_balances_rpc_runtime_api-29e9aee7500c8adb.rmeta --extern darwinia_primitives=/home/dev/darwinia/target/release/deps/libdarwinia_primitives-e4b4cc0f0e4055c9.rmeta --extern darwinia_rpc=/home/dev/darwinia/target/release/deps/libdarwinia_rpc-f5f21ff7052ff0a0.rmeta --extern darwinia_support=/home/dev/darwinia/target/release/deps/libdarwinia_support-788a2b73122dfd84.rmeta --extern frame_system_rpc_runtime_api=/home/dev/darwinia/target/release/deps/libframe_system_rpc_runtime_api-a7da121405d68176.rmeta --extern futures=/home/dev/darwinia/target/release/deps/libfutures-70a2c8f17446a59a.rmeta --extern log=/home/dev/darwinia/target/release/deps/liblog-d564efa95c4b564c.rmeta --extern pallet_im_online=/home/dev/darwinia/target/release/deps/libpallet_im_online-df364ea95520e7cc.rmeta --extern pallet_transaction_payment_rpc_runtime_api=/home/dev/darwinia/target/release/deps/libpallet_transaction_payment_rpc_runtime_api-c3dbe437f154531c.rmeta --extern codec=/home/dev/darwinia/target/release/deps/libparity_scale_codec-c527daf84968a121.rmeta --extern sc_authority_discovery=/home/dev/darwinia/target/release/deps/libsc_authority_discovery-cf8ff8b08b003b61.rmeta --extern sc_basic_authorship=/home/dev/darwinia/target/release/deps/libsc_basic_authorship-98d32fadc09e7cd7.rmeta --extern sc_chain_spec=/home/dev/darwinia/target/release/deps/libsc_chain_spec-e9ff5abe0762873d.rmeta --extern sc_client=/home/dev/darwinia/target/release/deps/libsc_client-6dfa83fd10d810c3.rmeta --extern sc_client_api=/home/dev/darwinia/target/release/deps/libsc_client_api-109aa8bc65d48228.rmeta --extern sc_client_db=/home/dev/darwinia/target/release/deps/libsc_client_db-29d0d9e34ab8f83c.rmeta --extern sc_consensus_babe=/home/dev/darwinia/target/release/deps/libsc_consensus_babe-7c09230ca4441974.rmeta --extern sc_executor=/home/dev/darwinia/target/release/deps/libsc_executor-84772efadeaf96d8.rmeta --extern sc_finality_grandpa=/home/dev/darwinia/target/release/deps/libsc_finality_grandpa-cea27eaed013f79b.rmeta --extern sc_network=/home/dev/darwinia/target/release/deps/libsc_network-7e0dd83fb537567b.rmeta --extern sc_service=/home/dev/darwinia/target/release/deps/libsc_service-c364184907cbaa16.rmeta --extern sc_telemetry=/home/dev/darwinia/target/release/deps/libsc_telemetry-a7e2c60311e3916c.rmeta --extern sc_transaction_pool=/home/dev/darwinia/target/release/deps/libsc_transaction_pool-06888daa5c6b740b.rmeta --extern serde=/home/dev/darwinia/target/release/deps/libserde-74e941e6879601ec.rmeta --extern serde_json=/home/dev/darwinia/target/release/deps/libserde_json-6d036f6df78aaae3.rmeta --extern sp_api=/home/dev/darwinia/target/release/deps/libsp_api-8d05f6ec162698b3.rmeta --extern sp_authority_discovery=/home/dev/darwinia/target/release/deps/libsp_authority_discovery-03418a4adfb040f9.rmeta --extern sp_block_builder=/home/dev/darwinia/target/release/deps/libsp_block_builder-0b5feff9bad998d5.rmeta --extern sp_blockchain=/home/dev/darwinia/target/release/deps/libsp_blockchain-08113766611ea1f7.rmeta --extern sp_consensus=/home/dev/darwinia/target/release/deps/libsp_consensus-2c259d378414d378.rmeta --extern sp_consensus_babe=/home/dev/darwinia/target/release/deps/libsp_consensus_babe-3e4172f92ecb4687.rmeta --extern sp_core=/home/dev/darwinia/target/release/deps/libsp_core-7f80c847f49694a2.rmeta --extern sp_inherents=/home/dev/darwinia/target/release/deps/libsp_inherents-194512131a3c3b13.rmeta --extern sp_offchain=/home/dev/darwinia/target/release/deps/libsp_offchain-3031b7fa5bbd732a.rmeta --extern sp_runtime=/home/dev/darwinia/target/release/deps/libsp_runtime-fd97923c3b45dc6d.rmeta --extern sp_session=/home/dev/darwinia/target/release/deps/libsp_session-fa9caaf783976604.rmeta --extern sp_transaction_pool=/home/dev/darwinia/target/release/deps/libsp_transaction_pool-f0235bd93a3c92c4.rmeta --extern substrate_prometheus_endpoint=/home/dev/darwinia/target/release/deps/libsubstrate_prometheus_endpoint-683afdc9e7c02485.rmeta -L native=/home/dev/darwinia/target/release/build/clear_on_drop-8b68bc7a28c0b6f9/out -L native=/home/dev/darwinia/target/release/build/jemalloc-sys-2f2a4e887bba4371/out/build/lib -L native=/home/dev/darwinia/target/release/build/backtrace-sys-6aaafca51d55a11e/out -L native=/home/dev/darwinia/target/release/build/ring-504546fc4340c37d/out -L native=/home/dev/darwinia/target/release/build/libz-sys-ff199467329df948/out/build -L native=/home/dev/darwinia/target/release/build/substrate-wasmtime-runtime-44d8c50330b5ec50/out -L native=/home/dev/darwinia/target/release/build/zstd-sys-f023f25a19f042fe/out -L native=/home/dev/darwinia/target/release/build/librocksdb-sys-65d4b1beaa416bf4/out -L native=/home/dev/darwinia/target/release/build/librocksdb-sys-65d4b1beaa416bf4/out` (signal: 9, SIGKILL: kill)
> </code></pre>
> </details>

Then get a rocksdb lib instead compile it yourself, just like libopenssl.

**Comment by yanganto** [comment]
It maybe a good time to fix the CentOS part of bootstrap script, so the next CentOS user can compile much easier. :)
https://github.com/darwinia-network/darwinia/blob/master/.maintain/bootstrap.sh#L11
