### ISSUE TITLE
Question: different `CheckedExtrinsic ` usage

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#446]
In darwinia crab  and  kusama runtime, it is using:
```
pub type CheckedExtrinsic = generic::CheckedExtrinsic<AccountId, Nonce, Call>;
```

The types does not match  expected.

In substrate:

```
pub type CheckedExtrinsic = generic::CheckedExtrinsic<AccountId, Call, SignedExtra>;
```

**Comment by HackFisher** [comment]
It seems that the ```CheckedExtrinsic``` type defined in crab and kusama runtime are not used in any other place?

**Comment by AurevoirXavier** [comment]
After talking to Shawn. 

We think these line are dead code which was used in previous version.

**Comment by HackFisher** [comment]
Would like to keep this issue until dead codes are removed or updated.

It seems that codes in Substrate are only used for benches
```
/// Extrinsic type that has already been checked.
pub type CheckedExtrinsic = generic::CheckedExtrinsic<AccountId, Call, SignedExtra>;
```

**Comment by AurevoirXavier** [comment]
Yes, and he suggest me to open a PR to remove those line in polkadot.
