### ISSUE TITLE
Why nextFeeMultiplier is -1 in Kusama and Crab

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#447]
Queried value from chain state is Fixed128 -1,000,000,000,000,000,000

Fixed128 is a signed fixed-point number with fixed-point accuracy of 10 ** 18, so it is -1 actrully, and removed all length fee and weight fee as a result, only base fee are computed.

**Comment by HackFisher** [comment]
https://w3f-research.readthedocs.io/en/latest/polkadot/Token%20Economics.html#setting-transaction-fees

**Comment by HackFisher** [comment]
```
///   diff = (previous_block_weight - target_weight)/max_weight
///   v = 0.00004
///   next_weight = weight * (1 + (v * diff) + (v * diff)^2 / 2)
```

Here ```(v * diff) + (v * diff)^2 / 2``` is the nextFeeMultiplier. It is not related to last nextFeeMultiplier, so should now using last multiplier to add it.

```
if positive {
			// Note: this is merely bounded by how big the multiplier and the inner value can go,
			// not by any economical reasoning.
			let excess = first_term.saturating_add(second_term);
			multiplier.saturating_add(excess)
		} else {
			// Defensive-only: first_term > second_term. Safe subtraction.
			let negative = first_term.saturating_sub(second_term);
			multiplier.saturating_sub(negative)
				// despite the fact that apply_to saturates weight (final fee cannot go below 0)
				// it is crucially important to stop here and don't further reduce the weight fee
				// multiplier. While at -1, it means that the network is so un-congested that all
				// transactions have no weight fee. We stop here and only increase if the network
				// became more busy.
				.max(Fixed128::from_natural(-1))
		}
```

**Comment by HackFisher** [comment]
```
let diff(n) = (previous_block_weight(n-1) - target_weight)/max_weight;
let multiplier(n) = (v * diff) + (v * diff)^2 / 2
then weight(n) should be weight * (1 + multiplier(0)) * (1 + multiplier(1)) * (1 + multiplier(2)) * .... multiplier(n) = weight * (1 + total_mulitplier(n))

total_mulitplier(n) = (total_mulitplier(n - 1) + 1) * multiplier(n) - 1
```

**Comment by kianenigma** [comment]
> then weight(n) should be weight * (1 + multiplier(0)) * (1 + multiplier(1)) * (1 + multiplier(2)) * .... multiplier(n) = weight * (1 + accumulate_mulitplier(n))

This is not correct. The weight of each transaction is only a function of of the previous multiplier. I think this whole notion of `multiplier(n)` is confusing. There is only ever two multiplier. `current`, and `next`, which is a direct function of  `current`, hence you get `Convert<Fixed128, Fixed128>`, which basically translates to what I just said 

https://github.com/paritytech/substrate/blob/dbf2163250833e6ac898e7f6c3c8f89f08a7c19d/bin/node/runtime/src/impls.rs#L72-L73

Now, taking this into account, look at this code: 

https://github.com/paritytech/substrate/blob/dbf2163250833e6ac898e7f6c3c8f89f08a7c19d/bin/node/runtime/src/impls.rs#L95-L113

`next = current * (1 + first_term + second_term)`

which is 

`next = current  + current * (first_term + second_term)`

which is exactly what we have for example in the positive case 

```rust
 	let excess = first_term.saturating_add(second_term); 
 	multiplier.saturating_add(excess) 
```

same goes for the negative one. 

```rust 
 	let negative = first_term.saturating_sub(second_term); 
 	multiplier.saturating_sub(negative) 
```

--- 

All in all, I think you are. a bit confusing things with the notion of `(n)` and this chaining that you introduced. Happy to discuss further if needed.

**Comment by HackFisher** [comment]
@kianenigma The word of multiplier and accumulate_mulitplier did confuse a lot, let me give some more explanation. 

> https://w3f-research.readthedocs.io/en/latest/polkadot/Token%20Economics.html#setting-transaction-fees
> 
> ctraffic←ctraffic⋅(1+v(s−s∗)+v2(s−s∗)2/2)

Comparing the ```ctraffic``` transition formula introduce int the research page and the implemention, the ```ctraffic``` is  actually ```NextFeeMultiplier::get() + 1```. 

https://github.com/paritytech/substrate/blob/dbf2163250/frame/transaction-payment/src/lib.rs#L160

```
// the adjustable part of the fee
let adjustable_fee = len_fee.saturating_add(unadjusted_weight_fee);
let targeted_fee_adjustment = NextFeeMultiplier::get();
let adjusted_fee = targeted_fee_adjustment.saturated_multiply_accumulate(adjustable_fee.saturated_into());
```

My understanding of ```ctraffic``` as following should stand:
```
ctraffic(n) = ctraffic(n - 1) * (1+v(s−s∗)+v2(s−s∗)2/2) = ctraffic(n - 1) * ctraffic(n - 2) ..... *ctraffic(0)
```

```TargetedFeeAdjustment``` is actually used to adjust ```NextFeeMultiplier```, which is ```ctraffic(n) - 1```

(NextFeeMultiplier + 1) should follow adjust op``` *  (1+v(s−s∗)+v2(s−s∗)2/2)```, but current ```TargetedFeeAdjustment``` is just add/sum the value ```+ v(s−s∗)+v2(s−s∗)2/2```

**Comment by kianenigma** [comment]
> the ctraffic is actually NextFeeMultiplier::get() + 1.

Nope, ctraffic is just `NextFeeMultiplier`. 

> ctraffic(n) = ctraffic(n - 1) * (1+v(s−s∗)+v2(s−s∗)2/2) = ctraffic(n - 1) * ctraffic(n - 2) ..... *ctraffic(0)


Okay `ctraffic(n) = ctraffic(n - 1) * (1+v(s−s∗)+v2(s−s∗)2/2)` is correct but how are you concluding that it is equal to ` ctraffic(n - 1) * ctraffic(n - 2) ..... *ctraffic(0)`? I can't follow. 

> (NextFeeMultiplier + 1) should follow adjust op * (1+v(s−s∗)+v2(s−s∗)2/2), but current TargetedFeeAdjustment just add/sum the value v(s−s∗)+v2(s−s∗)2/2 for NextFeeMultiplier using adjust op + (v(s−s∗)+v2(s−s∗)2/2)

I think you are you are mistaking the `+1` as mentioned in the beginning of the comment.

**Comment by HackFisher** [comment]
> Nope, ctraffic is just NextFeeMultiplier. And one way or another lets only discuss things in the context of the formula in substrate:

```
targeted_fee_adjustment.saturated_multiply_accumulate(adjustable_fee.saturated_into());
```
targeted_fee_adjustment returns a saturated `int + (self * int)`, which should be ```NextFeeMultiplier::get() + 1```

> Okay ctraffic(n) = ctraffic(n - 1) * (1+v(s−s∗)+v2(s−s∗)2/2) is correct but how are you concluding that it is equal to ctraffic(n - 1) * ctraffic(n - 2) ..... *ctraffic(0)? I can't follow.

Sorry, here  I made a mistake, should be 

```
ctraffic(n) = ctraffic(n - 1) * (1+v(s−s∗)+v2(s−s∗)2/2)[n] = (1+v(s−s∗)+v2(s−s∗)2/2)[n] * (1+v(s−s∗)+v2(s−s∗)2/2)[n - 1] * (1+v(s−s∗)+v2(s−s∗)2/2)[n - 2] ..... (1+v(s−s∗)+v2(s−s∗)2/2)[0]
````

**Comment by kianenigma** [comment]
Okay I think I realized why you insist that there is a +1 missing here: what we store as `FeeMultiplier`, we don't multiply it by the fee at the end

https://github.com/paritytech/substrate/blob/dbf2163250833e6ac898e7f6c3c8f89f08a7c19d/frame/transaction-payment/src/lib.rs#L160

we call multiply_accumulate on it which basically means `x.multiply_accumulate(y) = x * ( 1 + y )`. 

this should clarify everything.

**Comment by AurevoirXavier** [comment]
@kianenigma 

So the formula turns into

```
// according to
ctraffic * [base_fee + type(tx) * length(tx) + weight(tx)]
// and
x.multiply_accumulate(y) = x * (1 + y)

// `x` is `ctraffic`?
// `1 + y` is `[base_fee + type(tx) * length(tx) + weight(tx)]`?
// what's the `+ 1` represent for?
```

**Comment by shawntabrizi** [comment]
I think @HackFisher and @AurevoirXavier should be careful taking the research paper as 100% correct. I dont know which came first (the code or the research paper), but I can already say that the research paper is inaccurate given the fact that the base fee is outside of any multiplier in our code, and this is intentional.

As for `saturated_multiply_accumulate` versus `saturated_mul`, we need only look at the situation when targeted fee adjustment is `-1` to see that `saturated_multiply_accumulate` is correct:

```
adjusted_fee
    = (-1).saturated_multiply_accumulate(adjustable_part_of_fee)
    = adjustable_part_of_fee - adjustable_part_of_fee
    = 0
```

as intended. If we did not use saturated multiply accumulate, we would get a negative adjusted fee.

**Comment by HackFisher** [comment]
> I think @HackFisher and @AurevoirXavier should be careful taking the research paper as 100% correct. I dont know which came first (the code or the research paper), but I can already say that the research paper is inaccurate given the fact that the base fee is outside of any multiplier in our code, and this is intentional.
> 
> As for `saturated_multiply_accumulate` versus `saturated_mul`, we need only look at the situation when targeted fee adjustment is `-1` to see that `saturated_multiply_accumulate` is correct:
> 
> ```
> adjusted_fee
>     = (-1).saturated_multiply_accumulate(adjustable_part_of_fee)
>     = adjustable_part_of_fee - adjustable_part_of_fee
>     = 0
> ```
> 
> as intended. If we did not use saturated multiply accumulate, we would get a negative adjusted fee.

@shawntabrizi 

We might need to do a migration to  reset```FeeMultiplier ``` from -1 to 1 if apply the changes I sugguested:

> Replacing saturated_multiply_accumulate with saturating_mul , and fix the TargetedFeeAdjustment using op
> ```* (1+v(s−s∗)+v2(s−s∗)2/2)```

If the implementation and meaning of ```FeeMultiplier ``` is initially wrong, we may need to fix this way.

As of research paper, except the part of base_fee, the ```ctraffic ``` looks good to me.

**Comment by kianenigma** [comment]
I will dig up why we decided to implement this feature with this multiply_accumulate, but all in all it should be unrelated to your overall issue; the -1 is okay since most blocks are empty. FYI you can disable this if you pass `type WeightFeeMultiplier = ()` to the system trait.

**Comment by AurevoirXavier** [comment]
https://github.com/paritytech/substrate/pull/6334

**Comment by AurevoirXavier** [comment]
https://github.com/darwinia-network/darwinia-common/pull/200
