### ISSUE TITLE
What is bad blocks used for?

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#450]
For example:
https://github.com/paritytech/polkadot/pull/1055

**Comment by AurevoirXavier** [comment]
> it's a blocklist of blocks you never want to include in your chain 
> for example in this case if you make a runtime upgrade that bricks your chain 
> you can clear history of nodes that saw the block, add the bad block to bad blocks and then restart other nodes 
> they will ignore the block if they see it 

Btw, resync needed.
