### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.'

### ISSUE THREAD

**Issue by WoeOm** [darwinia-network/darwinia#458]
![image](https://user-images.githubusercontent.com/7368203/84559007-e5fdac80-ad69-11ea-8b26-1dd039dc980e.png)

Sys: centos 
Implementation:  0.6.0
Dependency: Substrate 2.0 alpha.8

**Comment by HackFisher** [comment]
```

cl-shanghai | - | Beijing | 0.6.0 | 43 | 0 |   |   | #489,135 | 0xeeabbbff851966bc54172a14f0152bb312b9aa0ade81f59bf693f50bd386ab03 | 4.796s | ∞ |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Karamba \| 5CRABQw7P9 | - | Nuremberg | 0.6.0 | 11 | 0 |   |   | #489,135 | 0xe1808be9945a96d40ad490087c5e1897152b6c28f7e7ed9fe052f28b0e324c12 | 4842s | ∞ |  
zealot \| 5CRABvh1GG | - | Nuremberg | 0.6.0 | 45 | 0 |   |   | #489,135 | 0xd97c2d5a2922880a2c1b234044ae1b8cc6d6baa9b5ac136a68ecc98698c8bf1d | 22542s | ∞ |  
🔱Masternode24 \| 5CRABnQZeu | - | Nuremberg | 0.6.0 | 38 | 0 |   |   | #489,135 | 0x6793fb7157c2443b9c153e6b274723c2b5f316249268b87e52fa7b930daf2583 | 2200s | ∞ |  
168NODE | - | Hangzhou | 0.6.0 | 30 | 0 |   |   | #489,135 | 0x4641437d807979b004a104c8a1c9c175a15ed0e49bb0b8575e8cb15c1435fb60 | 3.525s


```

**Comment by HackFisher** [comment]
[6月13号节点问题数据分析.pdf](https://github.com/darwinia-network/darwinia/files/4781588/6.13.pdf)

There are some statistics of validator count from subscan, but the validator count of session 850 and 851 are 32, which are different with the grandpa authorities set in that session, seems to be unusual, need further checking @freehere107

**Comment by HackFisher** [comment]
[CCAA3D00-680A-4cca-9D27-8BAAFDDE074A.txt](https://github.com/darwinia-network/darwinia/files/4781610/CCAA3D00-680A-4cca-9D27-8BAAFDDE074A.txt)


Some debug log crawled by @AurevoirXavier using 0.6.0 client syncing?

**Comment by freehere107** [comment]
I checked again 

session 851 ,block 489347

```
[
  "80a5d9612f5504f3e04a31ca19f1d6108ca77252bd05940031eb446953409c1a",
  "c4429847f3598f40008d0cbab53476a2f19165696aa41002778524b3ecf82938",
  "b4f7f03bebc56ebe96bc52ea5ed3159d45a0ce3a8d7f082983c33ef133274747",
  "e0785340e721a52a5e406c3381a03ead07afb38ac447edc53267a4a0424b8176",
  "b62d88e3f439fe9b5ea799b27bf7c6db5e795de1784f27b1bc051553499e420f",
  "762fd1b5bd1db180f27e9ee1c7a4196d85b86c6f9f55048e7733d4816bc2ff57",
  "14dc9b8578ff0fca751df750341cb7eb867c3a3420023e9049a184d0f6d2d86e",
  "a6f7230e743089cdf1257e973fd65691ddcb4aa62ab5b0d579c0708d6fc28e6a",
  "2ac9219ace40f5846ed675dded4e25a1997da7eabdea2f78597a71d6f3803148",
  "0f99850f381fdfb5b965617619e59ed082a4515c22967c9c1c94621969362aba",
  "321dfc7c69828013a840fa3010f71b78913c61eb6e510bc2448c132849d03359",
  "0f9986176437e7e354fb505884f4b3286aea730ea7840f25d722558bb93c4ffb",
  "cc1c4511ecea69f32fba0f8dcf4668284c5ed47a3895b7523294a0646b4abc77",
  "be60e61c9a14ee4682d798c883dfec2df4ff34ad1c2e1bc8efcaa5a96f021355",
  "e8692be8e3c3af9e9eba0e6d6c73e2ad825ea1e5515f81726734798b6093e803",
  "cec66c9be4c0500c5da90cb87d1d0af693da4d5fc9bf0e43ec6195cf7ee4d650",
  "6482213046a034a1fbed5786a5bfac55782c7edfa9937ccb3d89ca28ab77c647",
  "9762bb70f3ea9caee72ac4b3bf2076dfb8f2df4e9b4aa120ed2c0d120d659c2f",
  "f6e367a71d6b817abfefd1338dbe5fd78f3f1816f237e4931d70c54b76351607",
  "ee6c36f4610725f262ebcf8ad3685603bc7d3110b6f6ff480e392f950c09ec7f",
  "b61c73bc97b9ee9be396c585ba7d4df131e5eeecf5e1cd8732214c60de9d9909",
  "6e6844ba5c73db6c4c6b67ea59c2787dd6bd2f9b8139a69c33e14a722d1e801d",
  "b858cc05d58b332d0ca1c15dfca82599ce593fbac0997a99c9cf07c7f0777d3f",
  "0f998513444a7c70ee486cc2d8d5546c388c982af8b6f701580007cd4dbf2c65",
  "ca3bace1d97d5e997970fa351059c8580ce87991e71dc640ad5234b66c8cad25",
  "10d904a7b054b178813f165ff68820b762cc8740d05baf4d15d1373c63720a49",
  "4163d166770524487407fb9259e1d70e2891e100cf9e24effd5a51aae91ba417",
  "cd859d3ddacba3ad211d9f6f209954649cb4e6d69c9d2d73e7651bd51fc28709",
  "d24ae3c166a2fefd91dc4b74caac5894f6ce738643d203adb0e0f4a84c011f16",
  "38d04d535811d985d12b6a247bf7b5c20340153b30dcb9c6372312efdd991bd1",
  "ca7c2c9dbf41ec177c654bd1cfc354c448e8d3f4f1f880088a12eab5bb3faccc",
  "4cc2fffa77764557754a249e577c86700e45442cc10032dade5489c02add7006",
  "522dec17f772828eaa4719764cf057117614a80912ec5465087ee53c1ad3941d",
  "b6d2afc3783b780b40144cd30e64f3934ab5ffa666bae9d66d0d6b12935ec23d",
  "4ee6172cb89e63801666c174eeedc51e9abe7e5823d31d1715c814138c0e4d7a",
  "0f99812c1e55b1e0e81c9b583f972f1efd205889d9baa97cc7d28544b866c9f5",
  "9e5eb1719c7f3896b5a71cca449bfc591cac82fd24b82ac59db703d470802ef3",
  "60e2feb892e672d5579ed10ecae0d162031fe5adc3692498ad262fb126a65732",
  "c6a8cab00d9f7a8b828ef0b8c982bb7374c261ee6453950c296b14d53ec15e6c",
  "5849119b2908a340c1272af61d51121a8cb79b9fdc32a18212c1085fc9a40f70",
  "0f99845c37f38d70d0d28c78016a8ac0623096c32b19605a342dcdd3483ccada",
  "0f998dc36dde304b0e6770f7bca9342c3b070e20d1f032a00a9e66efc89badb9",
  "0f998833267ae4a1c65cc142c206b01e0db39923316d64f84f46bf9ef4e04923",
  "c2f128cb933e60eb173706a54c0d5b15de0462bd3cb70e77fdd3996c3a1e787b",
  "0f998d4d11d273909f1b5f659201245329d5c883914a22ed5b109b8e088f602f",
  "0f998cb2bded511a9bc7c9ace3b0962b28ea29b1f92d1a6e6e51078be5c87ae9",
  "84921c675d324f77a192b8d9007a2f399b65277daa92ee0adb2bdc406a76e26d",
  "411bb2a7d5317a9fb3c005c060dc7f75826d651cedf3102f859c15f1b7599235",
  "0f9982fa6da647bdfdc6005dd6bb8b9bdafc722d697f9c05761ba468587ad0c4",
  "0f998989cd826bd7b11c6da5b9b881d0dae9d6098841e2fa344feb6f1633cc35",
  "0f998a938141d280e299cdb022d0f66583d9ab6def493292c953caf22e18aa5e",
  "0f99883845010c5678ed849d3804825b14fd627ddc034de93d4ddd76bd0b4dd3",
  "0f998a4edb7ef66bcd454d84f1d97f459a05a7bc7adfd40fe60144974d698206",
  "d7d7987b91edf4836feb8c262c3cd6dbb14e1caa693833fac646ffb54abed94a",
  "0f9980efd1348abea6eb99615973aac8ec4e4eaa20a384b6cc14d924ccfb4d30",
  "0f9980577c10312720095b9ebf94117eefc1e855bb0829b16555917cfeb568db",
  "fce6923ace2bb25f44fc064d51f7e5a054c0cc458f163c9ad3156abe3bcf2942"
]
```

**Comment by freehere107** [comment]
session 851 ,block 489571, Validators count 57
```
[
  "b4f7f03bebc56ebe96bc52ea5ed3159d45a0ce3a8d7f082983c33ef133274747",
  "e0785340e721a52a5e406c3381a03ead07afb38ac447edc53267a4a0424b8176",
  "b62d88e3f439fe9b5ea799b27bf7c6db5e795de1784f27b1bc051553499e420f",
  "14dc9b8578ff0fca751df750341cb7eb867c3a3420023e9049a184d0f6d2d86e",
  "a6f7230e743089cdf1257e973fd65691ddcb4aa62ab5b0d579c0708d6fc28e6a",
  "ca7c2c9dbf41ec177c654bd1cfc354c448e8d3f4f1f880088a12eab5bb3faccc",
  "38d04d535811d985d12b6a247bf7b5c20340153b30dcb9c6372312efdd991bd1",
  "cec66c9be4c0500c5da90cb87d1d0af693da4d5fc9bf0e43ec6195cf7ee4d650",
  "b6d2afc3783b780b40144cd30e64f3934ab5ffa666bae9d66d0d6b12935ec23d",
  "b858cc05d58b332d0ca1c15dfca82599ce593fbac0997a99c9cf07c7f0777d3f",
  "ca3bace1d97d5e997970fa351059c8580ce87991e71dc640ad5234b66c8cad25",
  "d24ae3c166a2fefd91dc4b74caac5894f6ce738643d203adb0e0f4a84c011f16",
  "4cc2fffa77764557754a249e577c86700e45442cc10032dade5489c02add7006",
  "0f99845c37f38d70d0d28c78016a8ac0623096c32b19605a342dcdd3483ccada",
  "5849119b2908a340c1272af61d51121a8cb79b9fdc32a18212c1085fc9a40f70",
  "0f998989cd826bd7b11c6da5b9b881d0dae9d6098841e2fa344feb6f1633cc35",
  "84921c675d324f77a192b8d9007a2f399b65277daa92ee0adb2bdc406a76e26d",
  "0f9980a712099708b421cbfc184956b25d06365496f480f60a98e182ff09b50a",
  "0f99883845010c5678ed849d3804825b14fd627ddc034de93d4ddd76bd0b4dd3",
  "0f998d47c800c8f7bcc233d27f81e306ca247bdabb959a1f07f737dc8715e7e0",
  "f9c563ad33f6152d6a3c1eac1c4549771dc84dfc4b4dfd7283b5cd5f4df75a4b",
  "2a52a3adf6056b1ee8701d783006981edf986c5d29e5e3b829e921901277fb63",
  "38ba7e16fc711be6edb5bc8d344311c19be08253a7ca5bae27ff9d52c6334617",
  "0f99872a18855ed6b3ac3f2cc77409918a38d0aeb7b2bdb3716a0bbb370444be",
  "0f998daa3f785d1653e520d3f58f04c6f46269f62898185a702a4f9570b730a3",
  "8a9673ef43c3f41d8b772fd89a5d9abfa21afa4d9ecdeff1d182beb1b8e76b14",
  "0f9980c64699fb44f34ee07e37e619e90fd172770c6f9b819ca5cf21494ef604",
  "0f997fc196a26766035e459285d36c015f255d4fa0295dc76d0919262c867baa",
  "0f9983d06bbcbb61194968032614eccba4251f107938c305057d106dcd7e40f9",
  "0f9980503ea487af0bbf933fa254820ce27791063bc9a18cff42412292c7c816",
  "298f64dabf619a3832cd6fa627c72d55e80640ec11497fc47549d13c334d58bc",
  "0f9980cdf9eaa44aa9926d3c356b5298cdf7b2d408ce55e13454558ceec570dd",
  "0f9985dfd47754d1ae6711cfb5ad85241b4e3b82e70fae4ff2c879648ee4a1de",
  "0f998192d2920aa5cee9ab31860e16889eba85a0c835473b83a113ea32fc57c6",
  "241a9c2aa8a83e1c5f02fc2b7112bd1873249a8e55a4f919c7d42cf1164be35c",
  "e30eeb884dcd06c179fc94ae6209ad5ed8ddbb2bf0729bd72444f02ed2672544",
  "0f998014339aecdb10f1324e62e6f929d76d10d18a6939d3b4399c32fa4f8042",
  "0f9980a4be3c19643d19cfe58f8b6eb0847400ef162f7233f1ecff5120d6a3d7",
  "0f9980c6f040aae9742b93f46889c13f10c8ab11694f0a9288c25bb6016b3159",
  "0f998069502dc37d4d5d29570093f304ea8eb191cff2525793c05d5edd0dc9c3",
  "0f9980255c4b8899191a6b2fe3eb41c35c670b28aaf978f04879f6cfa60ff55c",
  "321dfc5213ed8e896ef3511f10140e51bc4b96367db81248a8d50f7629d536f0",
  "eeedb4805e781b16db87edc6fc2bb0982bf70a435e6a5acac37ede09131d8b8b",
  "0f9981f7c20ff93d581eb7f57132ff2f663d689aba07fd97a38a762235de1f5f",
  "0f9982ceab82a948f0d1a7d0023ed1d7c90203ff659c89c914a23b25d3d1a6cd",
  "0f998ad442637f6bb974c135e6db3b5234ef500077c160a7e087037493d3e353",
  "93e64f310f1978dde17ecf2fb91edc5bda666ca89b9427a09cb173d3fd26986a",
  "0f9980aac0271f3cf41b0a539c178fffefcf351195becee0c67f0af16c5042a3",
  "0f998a17889514a7920a381259ece610afeff88e506e37aeadcb2773f16801c1",
  "0f9983cf305f051dc8882aaf32bebff07e13c347d6f5d5ea34009636a950a0c5",
  "1acad5aa2f1acb679f99e0259968c2919666c79c60a2990929110c0482727334",
  "1f8460d707beea632db7c3f08e9bd7a470c7f7eb21498fb78aaaad0e641c6d3a",
  "b86d10e54f90b0de3eec4116a24d44778cc9f295e599e0fc2a01bb1ec58e95b1",
  "1c344a574b8be1d02089c9d0941ce730d36876361518285ffa593702dd0a7c3a",
  "0f99883e847096297175aeb3b5cee7ec83e8c744b858cf967d8d303829cf72fe",
  "c45f075b5b1aa0145c469f57bd741c02272c1c0c41e9518d5a32426030d98232",
  "7f25e6d11bcee0f11fadf4355821c805334d086c0d36e7561f70e9f0d1a8f536"
]

```

**Comment by freehere107** [comment]
There are some errors in the statistics, I recalculated some
| session_id | era | start_block |count_validators|
| ------------- | ------ | ------- |-----|
|864|158|496268|44
|863|158|495684|44
|862|158|495105|44
|861|157|494509|32
|860|157|493909|32
|859|157|493310|32
|858|157|492712|32
|857|157|492123|32
|856|157|491525|32
|855|156|490927|32
|854|155|490552|56
|853|154|490197|56
|852|153|489878|57
|851|152|489571|57
|850|151|489347|57
|849|150|489135|57
|848|150|488574|57

**Comment by HackFisher** [comment]
The trace logging method in this issue might be helpful:
https://github.com/paritytech/polkadot/issues/413#issuecomment-553294078

**Comment by freehere107** [comment]
with the 0.6.0 version, the new node resync will also encounter the same panic

Version: 0.6.0-d0942cf-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libstd/panicking.rs:474
   2: std::panicking::begin_panic
   3: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_block
   4: <crab_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,crab_runtime::Call,sp_runtime::MultiSignature,(frame_system::CheckSpecVersion<crab_runtime::Runtime>, frame_system::CheckTxVersion<crab_runtime::Runtime>, frame_system::CheckGenesis<crab_runtime::Runtime>, frame_system::CheckEra<crab_runtime::Runtime>, frame_system::CheckNonce<crab_runtime::Runtime>, frame_system::CheckWeight<crab_runtime::Runtime>, pallet_transaction_payment::ChargeTransactionPayment<crab_runtime::Runtime>, pallet_grandpa::equivocation::ValidateEquivocationReport<crab_runtime::Runtime>, darwinia_eth_relay::CheckEthRelayHeaderHash<crab_runtime::Runtime>)>>>>::execute_block
   5: std::panicking::try::do_call
   6: __rust_maybe_catch_panic
             at rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libpanic_unwind/lib.rs:86
   7: std::thread::local::LocalKey<T>::with
   8: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
   9: sc_executor::wasm_runtime::RuntimeCache::with_instance
  10: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  11: sp_state_machine::StateMachine<B,H,N,Exec>::execute_aux
  12: sp_state_machine::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  13: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  14: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  15: sp_api::runtime_decl_for_Core::execute_block_call_api_at
  16: sp_api::Core::execute_block
  17: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
  18: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
  19: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
  20: sp_consensus::import_queue::import_single_block
  21: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  22: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  23: <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  24: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  25: std::panicking::try::do_call
  26: __rust_maybe_catch_panic
             at rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libpanic_unwind/lib.rs:86
  27: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  28: <std::future::GenFuture<T> as core::future::future::Future>::poll
  29: std::thread::local::LocalKey<T>::with
  30: futures_executor::local_pool::block_on
  31: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  32: std::panicking::try::do_call
  33: __rust_maybe_catch_panic
             at rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libpanic_unwind/lib.rs:86
  34: tokio::runtime::task::raw::poll
  35: tokio::runtime::blocking::pool::Inner::run
  36: tokio::runtime::context::enter
  37: std::sys_common::backtrace::__rust_begin_short_backtrace
  38: std::panicking::try::do_call
  39: __rust_maybe_catch_panic
             at rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libpanic_unwind/lib.rs:86
  40: core::ops::function::FnOnce::call_once{{vtable.shim}}
  41: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/liballoc/boxed.rs:1017
  42: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/liballoc/boxed.rs:1017
      std::sys_common::thread::start_thread
             at rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libstd/sys/unix/thread.rs:80
  43: start_thread
  44: clone


Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', runtime/crab/src/lib.rs:1

This is a bug. Please report it at:

	https://github.com/darwinia-network/darwinia/issues/new

**Comment by AurevoirXavier** [comment]
```rust
2020-07-25 22:36:48 💔 Error importing block 0x6fb9d9d6741073965531e18fe7041558fc8ba61751f76406604b676088c5529c: Err(Other(ClientImport("Import failed: Execution: Runtime panicked: Storage root must match that calculated.")))
2020-07-25 22:36:48 💔 Error importing block 0x95b99e90134fea0a49c5f3b2ae646a064e8c59f280a2b8e5c994257e9ec5383c: Err(UnknownParent)
2020-07-25 22:36:48 💔 Error importing block 0x90aa383c788757ff91081b708a7a25e497c6d8fc344e8acd934e1702f23e1ffc: Err(UnknownParent)
2020-07-25 22:36:48 💔 Error importing block 0x128c1b854c50566e42c031fb785c607bc244b5c6dd8e326d860344777177fe45: Err(UnknownParent)
2020-07-25 22:36:48 💔 Error importing block 0x689d2915dea04e0ba9efea2185db672999514694bbf81a6d77b290d3c7157725: Err(UnknownParent)
2020-07-25 22:36:48 💔 Error importing block 0xb52926e81f2ca7a765f4c59f985f3736c9738c3b6c8a902227fb9016491b7eb2: Err(UnknownParent)
2020-07-25 22:36:48 💔 Error importing block 0xcddff3139dc70d17e3061b78ef67f43bb585f5ce3d058670b7bd3a223fab5d9b: Err(UnknownParent)
2020-07-25 22:36:48 💔 Error importing block 0x34205a592852d7304225ad270b8eb31d3162572fe7c52a3dc9ca3c236199cb7d: Err(UnknownParent)
2020-07-25 22:36:48 💔 Error importing block 0xac978029feb3281d53f56160371d115d8cdb5de9bb3f752fe26c6d419a07b808: Err(UnknownParent)
```

**Comment by AurevoirXavier** [comment]
move to #481
