### ISSUE TITLE
Stop syncing issues: Execution: Memory: tring to access region [1048576..1048588] in memory [0..0]

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#459]
After the restart, the number of peers is growing, and then they disappear.

Validator node or achieve node.

![photo_2020-06-13 16 44 37](https://user-images.githubusercontent.com/1070122/84564842-6e467680-ad97-11ea-95cf-ae814af64c36.jpeg)

**Comment by AurevoirXavier** [comment]
I think the force restart broke the DB files.

**Comment by AurevoirXavier** [comment]
Could you reproduce this?

If not I'll going to close this issue.
