### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.'

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/darwinia#460]
## Spec

Crab node panic after restarting:

<details>
<summary>
Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.'
</summary>
<pre><code>0|darwinia  | 2020-06-13 21:18:07 Block prepare storage changes error:
0|darwinia  | Execution(RuntimePanicked("Storage root must match that calculated."))
0|darwinia  | 2020-06-13 21:18:07 💔 Error importing block 0x6fb9d9d6741073965531e18fe7041558fc8ba61751f76406604b676088c5529c: Err(Other(ClientImport("Import failed: Execution: Runtime panicked: Storage root must match that calculated.")))
0|darwinia  | 2020-06-13 21:18:07 ⚙️  Syncing  0.0 bps, target=#497017 (21 peers), best: #489135 (0xeeab…ab03), finalized #489133 (0x7cf9…07e6), ⬇ 158.4kiB/s ⬆ 23.2kiB/s
0|darwinia  | 2020-06-13 21:18:07 💸 new validator set of size 57 has been elected via ElectionCompute::Unsigned for era 151
0|darwinia  | Hash: given=4183747c4e02e1b7c15f0bac848d6292f9ea76ec4dfb7d6bf2cdd0a8fe13620c, expected=e8772b5bddf4c9713edb0fa94a42cfaa33107d9b7babffc2ac3e67386bae2039
0|darwinia  | ====================
0|darwinia  | Version: 0.6.0-d0942cf-x86_64-linux-gnu
0|darwinia  |    0: <unknown>
0|darwinia  |    1: <unknown>
0|darwinia  |    2: <unknown>
0|darwinia  |    3: <unknown>
0|darwinia  |    4: <unknown>
0|darwinia  |    5: <unknown>
0|darwinia  |    6: <unknown>
0|darwinia  |    7: <unknown>
0|darwinia  |    8: <unknown>
0|darwinia  |    9: <unknown>
0|darwinia  |   10: <unknown>
0|darwinia  |   11: <unknown>
0|darwinia  |   12: <unknown>
0|darwinia  |   13: <unknown>
0|darwinia  |   14: <unknown>
0|darwinia  |   15: <unknown>
0|darwinia  |   16: <unknown>
0|darwinia  |   17: <unknown>
0|darwinia  |   18: <unknown>
0|darwinia  |   19: <unknown>
0|darwinia  |   20: <unknown>
0|darwinia  |   21: <unknown>
0|darwinia  |   22: <unknown>
0|darwinia  |   23: <unknown>
0|darwinia  |   24: <unknown>
0|darwinia  |   25: <unknown>
0|darwinia  |   26: <unknown>
0|darwinia  |   27: <unknown>
0|darwinia  |   28: <unknown>
0|darwinia  |   29: <unknown>
0|darwinia  |   30: <unknown>
0|darwinia  |   31: <unknown>
0|darwinia  |   32: <unknown>
0|darwinia  |   33: <unknown>
0|darwinia  |   34: <unknown>
0|darwinia  |   35: <unknown>
0|darwinia  |   36: <unknown>
0|darwinia  |   37: start_thread
0|darwinia  |   38: __clone
0|darwinia  | Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /rustc/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/libstd/macros.rs:13
0|darwinia  | This is a bug. Please report it at:
0|darwinia  |   https://github.com/darwinia-network/darwinia/issues/new
0|darwinia  | 2020-06-13 21:18:07 Block prepare storage changes error:
0|darwinia  | Execution(RuntimePanicked("Storage root must match that calculated."))
0|darwinia  | 2020-06-13 21:18:07 💔 Error importing block 0x6fb9d9d6741073965531e18fe7041558fc8ba61751f76406604b676088c5529c: Err(Other(ClientImport("Import failed: Execution: Runtime panicked: Storage root must match that calculated.")))
<code></pre></details>

## Solution

Solved after removing the DB and restarting.

**Comment by HackFisher** [comment]
Dupe #458
