### ISSUE TITLE
v0.6.1 Generate via command dosen't work

### ISSUE THREAD

**Issue by wjdfx** [darwinia-network/darwinia#462]
Use latest version v0.6.1 generate session key show error : {"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}. even though use --unsafe-rpc-external parameter on the start command.

Validator: Bit Cat report.

**Comment by AurevoirXavier** [comment]
In substrate rc2, they remove this rpc call under the unsafe mode.

Try generate it with `--rpc-external`(make sure WITHOUT `--validator`). After that you could restart it with `--validator`.
