### ISSUE TITLE
The node stops running and reports an error

### ISSUE THREAD

**Issue by atinst** [darwinia-network/darwinia#465]
This is error log：
![WechatIMG9](https://user-images.githubusercontent.com/32417799/85003390-ba732b80-b188-11ea-8142-c6ba17a6c1fc.jpeg)
When I rerun the node, I am prompted that it cannot be started normally, which brings me a lot of trouble. Please make sure to fix this problem!
![WX20200618-17303711111111111](https://user-images.githubusercontent.com/32417799/85003903-73396a80-b189-11ea-811a-1c20676acd87.png)

**Comment by AurevoirXavier** [comment]
Check your db files.

Seems they're lost.
