### ISSUE TITLE
How to build one linux binary, refer polkadot practice

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#466]
Example:

https://github.com/paritytech/polkadot/releases/tag/v0.8.11

https://github.com/paritytech/polkadot/releases/download/v0.8.11/polkadot

**Comment by AurevoirXavier** [comment]
In their release CI, they just make a `cargo build`.

Not support all the linux distros. 

The key is picking an old version of gcc to obtain better compatibility.
