### ISSUE TITLE
Node upgrade high priority strategy concept mentioned in recent polkadot CC1 and substrate

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#467]
https://github.com/paritytech/polkadot/releases/tag/v0.8.12

https://github.com/paritytech/substrate/releases/tag/v2.0.0-rc4

https://github.com/paritytech/substrate/pull/6451

> Upgrade priority:❗ HIGH ❗ Please upgrade your node as soon as possible - due to change(s): Fix Babe secondary plain slots claiming (paritytech/substrate#6451)

**Comment by AurevoirXavier** [comment]
https://github.com/darwinia-network/darwinia-common/pull/200
