### ISSUE TITLE
Will validator been un-validate after been slash in one session and before era ends?

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#471]
If a validator didn't produce any block in current session and no online signals too, he is supposed be be slashed, but will not be unlisted from the validator set immediately.

So if he come back to online in the next session before era ends, could he continue produce blocks automaticly (without revalidate action).

**Comment by joshua-mir** [comment]
Correct, unless there are a significant number of validators offline simultaneously, there is no forced change to the validator set (if there is a significant number of simultaneously offline validators, an era change is forced).

This validator would not be selected next era, but can come back online during the current era.
