### ISSUE TITLE
Crab Network claim rewards has a high txfee 

### ISSUE THREAD

**Issue by WoeOm** [darwinia-network/darwinia#473]
![image](https://user-images.githubusercontent.com/7368203/87370742-61938900-c5b6-11ea-94dd-f1993ab1a38b.png)

staking.payoutStakers

**Comment by AurevoirXavier** [comment]
Seems the `WeightToFee` formula is correct.

But seems the bytes not working in previous version (don't know why).

**Comment by HackFisher** [comment]
> The `WeightToFee` formula is correct.
> 
> But seems the bytes fee not working in previous version (don't know why).

Might related to this issue: https://github.com/darwinia-network/darwinia/issues/447

Will progress after substrate dep get upgraded.

**Comment by AurevoirXavier** [comment]
No. The root cause is bytes fee.

**Comment by HackFisher** [comment]
I mean bytes fees are included in the adjustable fees, and multiplier is not working, could this be the reason why multiplier not working?

**Comment by AurevoirXavier** [comment]
But the fix for #447 was not included in RC2.

After I change the bytes fee from `10 * MILLI` to `10 * MICRO`, it looks good to me.

**Comment by AurevoirXavier** [comment]
```
xavier:
I check the formula. It's correct.
But I found the bytes fee is very expensive. And I didn't change that field.
Seems all the previous version didn't count bytes fee.

shawntabrizi:
👍️
i think byte fee was always counted, but with that PR you linked
we made it so that byte fee
is not effected by the multiplier
so byte fee before used to go to zero
and now it does not
but idk if you have the version where this matters
```

Don't know why.

So the solution is upgrade to RC4. And a hot fix is need, to low down the tx fee for Crab before the RC4 apply.

**Comment by HackFisher** [comment]
How to infer the type of ```adjusted_fee ``` in rust? u128 or Fixed128?

https://github.com/darwinia-network/substrate/blob/45b9f0a9cbf901abaa9f1fca5fe8baeed029133d/frame/transaction-payment/src/lib.rs#L178

**Comment by AurevoirXavier** [comment]
```rust
#[test]
fn Multiplier() {
	let len_fee: u128 = 50;
	let weight_fee: u128 = 50;
	let adjustable_fee = len_fee.saturating_add(weight_fee);
	println!("adjustable_fee: {:?}", adjustable_fee);

	let targeted_fee_adjustment: Multiplier = Multiplier::saturating_from_integer(-1);
	println!("targeted_fee_adjustment: {:?}", targeted_fee_adjustment);

	let adjusted_fee: u128 =
		targeted_fee_adjustment.saturating_mul_acc_int(adjustable_fee.saturated_into());
	println!("adjusted_fee: u128: {}", adjusted_fee);

	let adjusted_fee: i128 =
		targeted_fee_adjustment.saturating_mul_acc_int(adjustable_fee.saturated_into());
	println!("adjusted_fee: i128: {}", adjusted_fee);

	// FIXME: type annotations needed
	// 	adjusted_fee -> ?
	// 	adjusted_fee.saturated_into() -> u128
	//
	// ```rust
	// let adjusted_fee =
	// 	targeted_fee_adjustment.saturating_mul_acc_int(adjustable_fee.saturated_into());
	// let _infer: u128 = 1;
	// let _infer: u128 = _infer.saturating_add(adjusted_fee.saturated_into());
	// ```
}
```

**Comment by HackFisher** [comment]
Substrate is using u128 in ```weight_to_fee_with_adjustment ```

https://github.com/darwinia-network/substrate/blob/45b9f0a9cbf901abaa9f1fca5fe8baeed029133d/frame/transaction-payment/src/lib.rs#L188

**Comment by HackFisher** [comment]
There is a temp workaround by changing byte fee to 0, need to change back after this issue fixed or substrate get upgraded:

https://github.com/darwinia-network/darwinia/pull/472/files#diff-c853329fb7e0f885349d61e4b8c76080R164

**Comment by HackFisher** [comment]
There is a temp workaround by changing byte fee to 0, need to change back after this issue fixed or substrate get upgraded:

https://github.com/darwinia-network/darwinia/pull/472/files#diff-c853329fb7e0f885349d61e4b8c76080R164

**Comment by AurevoirXavier** [comment]
Fixed: https://github.com/paritytech/substrate/pull/6145
