### ISSUE TITLE
Time record when depositing RING in BlockNumber or Timestamp

### ISSUE THREAD

**Issue by hammeWang** [darwinia-network/darwinia#48]
### Bug description
For now, time in depositing ring is measured in seconds(timestamp).
But when it is set in genesis config, it comes with a problem that timestamp in genesis status is 0. 
Even if 'genesis' users have locked ring for 3 years, he/she immediately can withdraw the 'locked' ring without any punishment.

### How to fix
It can be fixed in 2 ways:
1.  time is measured in block number rather than in timestamp;
2. no `depositing` in genesis config. It depends on user behavior design.

**Comment by HackFisher** [comment]
More details about the launch of mainet.

1. Genesis Validators are required to do KTON lock-mapping before mainet, providing theire subkey for validating on darwinia network.

2. On the genesis file of darwinia network, these KTON balances and mapping will be write in the genesis, and ready for launch & validate.

This solution will help avoid the challenge of change and introduce block number to ```depositing```

**Comment by hammeWang** [comment]
closed. https://github.com/darwinia-network/darwinia/commit/aea03eb4644b302bab5fe2fb52b0b4aa22f85b28

**Comment by AurevoirXavier** [comment]
Try: reuse `BlockNumber` in #218
