### ISSUE TITLE
Darwinia - syncing bug

### ISSUE THREAD

**Issue by jimmy-tudeski** [darwinia-network/darwinia#482]
Hi Guys, I encoutered such bug. 

![2020-07-28 23_09_23-Greenshot](https://user-images.githubusercontent.com/68714636/88722376-6e23ef80-d127-11ea-806e-1e278ad75196.jpg)

**Comment by HackFisher** [comment]
Please use ```--execution=wasm``` as workaround for now.

Thanks.

**Comment by AurevoirXavier** [comment]
#481
