### ISSUE TITLE
Genesis Balances in Mainet Runtime

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#504]
- Ethereum Backing Module's Account, should be equal to the total supply of the ERC20 RINGs and KTONs. The genesis cross-chain mapping and gringott should be stopped before the mainet's genesis block. The ERC20 supply might decrease during genesis cross-chain mapping.
  + ERC20 RING: https://etherscan.io/token/0x9469d013805bffb7d3debe5e7839237e535ec483
  + ERC20 KTON: https://etherscan.io/token/0x9f284e1337a815fe77d2ff4ae46544645b20c5ff

- Tron Backing Module's Account, should be equal to the total supply of the TRC20 RINGs and KTONs. The genesis cross-chain mapping and gringott should be stopped before the mainet's genesis block. The TRC20 supply might decrease during genesis cross-chain mapping.
  + TRC20 RING: https://tronscan.org/#/token20/TL175uyihLqQD656aFx3uhHYe1tyGkmXaW
  + TRC20 KTON: https://tronscan.org/#/token20/TW3kTpVtYYQ5Ka1awZvLb9Yy6ZTDEC93dC

- CrabBacking Module's Account, a value <=40M RING, 0 KTON. Actual amount depend on how many RING swap-and-burned-to genesis, Refer #509, final left RING balance is 40M minus ```swap-and-burned-to genesis```

- Vesting Accounts
  + Foundation Vesting 400M,  5 years vesting period starts when mainnet launch
  + Team Vesting 300M, 1 year vesting period starts after 1 year since mainnet lanuch

- Other Accounts
  + The account balances using genesis cross-chain mapping from Ethereum and Tron. (Refer https://bapp.darwinia.network/)
  +  The account balances swap-and-burned-to genesis from Crab, Refer #509.
  + ~~The initial validator account balances for bootstraping. (Around 2000 RING each.)~~

The sum of the balances should be equal to 2000M.

**Comment by AurevoirXavier** [comment]
- [ ] swap and burn, waiting crab
- [ ] other account data, waiting evolution land 
- [ ] ethereum backing, deadline

**Comment by HackFisher** [comment]
Need to add a TronBacking module, and set the genesis for its module account id.
