### ISSUE TITLE
Final Check List

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#537]
### Code Hygiene + Genesis

- [x] Ensure that you are using a stable Substrate release.
- [x] Avoid using experimental or untested features of Substrate on genesis. 
- [x] Avoid deviating from defaults, especially in consensus-relevant code, unless you have a strong understanding of the side-effects.
- [x] If you have a custom SessionManager in your runtime, and are using frame_session, ensure/verify that it always gives the session module a complete set of keys.
- [x] Validate/audit your chainspec - ensure all configs are set and all values are correct (as expected in terms of data types and defaults). 
- [x] Validator Nodes in config should all have all required session keys - session keys in config should all be present on a node.
- [x] Sessions keys in config and in the runtime should be in the same order.
- [x] Sanity Check: Can you achieve finality with the number of validators you control at genesis?
- [x] Ensure as many dependencies as possible are crates following semver.
- [x] Sanity check your block time/slot length and session/epoch length - if you have too few blocks for a given validator set/session, sync will be slowed - and it is very difficult to change these specific constants post-launch.
- [ ] Benchmark any custom runtime functions - use benchmark values of existing runtime functions to specify accurate weights for your custom functions.
- [x] "Canary Net"s and public testnets are pretty critical to having networks with realistic/real state/value to better test things like migrations and the economics of your network - if it is not already in the plans, consider building and maintaining at least one.

---

### Launch Checklist

- [x] Are your genesis validators online and available? Do you have communication lines open to any third-party validators?
- [x] Consider having a private "dry run" where you execute the public chainspec unreleased on your own infrastructure. 

---

### Ops, Infrastructure, and Maintenance

- [x] What is your CI infrastructure like for node or runtime upgrades? Can you release a critical upgrade within a single era as determined in your chainspec, and have validators upgrade?

### Upgrades and Future-proofing

- [ ] What is your process for runtime upgrades? Are you familiar with using srtool (or equivalent) for deterministic builds? Users will need to verify runtime upgrades as well - you will need a process for communicating upgrades with them.
- [x] For any upstream Substrate update: are you educated on exactly how this update may change your runtime, where the migration code is, if any, and any other breaking changes or changes in behavior it may present? 
- [x] For any runtime upgrade that changes storage format: have you written migration code (for your own pallets) and determined how to safely perform the upgrade on your network? 
- [x] Sanity Check: verify that any linked data in your runtime is migrated in an order/manner that does not break links.
- [x] For all runtime upgrades: have you already tested out the runtime upgrades and any relevant migrations on a local or public testnet? 
- [x] Have you tested the latest version of the upgrade, including "minor last-minute changes"?

---

### Darwinia

- [x] Darwinia dev-net.
- [x] How tech.comm./council works? *disable on mainnet*?
- [x] How `Origin` works?
- [x] Disable swap and burn.
- [x] MultiSig tests.
- [x] Apps tests.
- [x] Update root key.

**Comment by AurevoirXavier** [comment]
Help me to finish the list.

@AlexChien @HackFisher @wuminzhe

**Comment by HackFisher** [comment]
- [ ] Checksum of the snapshot balances, including Crab, Ethereum, Tron

**Comment by AurevoirXavier** [comment]
Some addresses for partners to run validator
- [ ] Huobi

@HackFisher

**Comment by AurevoirXavier** [comment]
- [ ] Some addresses for partners to run validator at first stage.

**Comment by HackFisher** [comment]
- [ ] Fee checking

- Some corner cases:

Some account may only do KTON cross-chain transfer, but in this case, they will not have RING for fee payment.

**Comment by HackFisher** [comment]
- [ ] Change back the session time: https://github.com/darwinia-network/darwinia/pull/548/files#diff-15ec5ffd1b7b58431887583218e4c61dR40

**Comment by HackFisher** [comment]
- Checking Balances:
  + [ ] Total Supply
  + [ ] Genesis Balances of Backing module account id etc.

**Comment by HackFisher** [comment]
- [ ] remove the old migration in common

**Comment by HackFisher** [comment]
Decimals: 18

ERC20 ring totalSupply: 1141998248692824029753349753
ERC20 kton totalSupply: 55760225171204355332737
TRC20 RING totalSupply: 90403994952547849178882078
TRC20 KTON totalSupply: 1357120581926771954238

**Comment by AurevoirXavier** [comment]
- [] reset session length
