### ISSUE TITLE
Staking module currently are using for loop to pay dividends.

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#55]
Staking: (TODO: 需要用新算法替换目前的for循环清算，目前算法是跟波卡一样，这个会提交一个新的issue)

**Comment by HackFisher** [comment]
https://wiki.polkadot.network/en/latest/polkadot/node/guides/validator-payout/

**Comment by AurevoirXavier** [comment]
update link: [validator-payout](https://wiki.polkadot.network/docs/en/maintain-guides-validator-payout)

**Comment by AurevoirXavier** [comment]
https://github.com/paritytech/substrate/issues/4407

**Comment by AurevoirXavier** [comment]
https://github.com/paritytech/substrate/issues/4220
