### ISSUE TITLE
ERROR afg  GRANDPA voter error: Signing("Failed to sign GRANDPA 

### ISSUE THREAD

**Issue by atinst** [darwinia-network/darwinia#562]
![crying](https://user-images.githubusercontent.com/32417799/95820591-ea0efa80-0d5a-11eb-94ab-6d1f0e015d63.png)

**Comment by AsceticBear** [comment]
The same with https://github.com/darwinia-network/darwinia/issues/560, we are trying to fixing it.

**Comment by AsceticBear** [comment]
Thanks for your report. This issue is the same as https://github.com/darwinia-network/darwinia/issues/560, we are trying to fix it.
