### ISSUE TITLE
Stall symptoms of websocket node during runtime upgrating?

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#569]
[websocket.log](https://github.com/darwinia-network/darwinia/files/5383480/websocket.log)

Comments from @wi1dcard 
> 1）CPU 在北京时间 15:30 ~ 15:50 左右有普遍升高，但升高的幅度不同
> 2）Websocket 卡住可能是由于 CPU 达到限制导致的，websocket 节点 CPU 使用率持续高，原因未知。重启节点后恢复正常。
> 3）在 CPU 升高的时间范围 15:30 ~ 15:50 内，所有节点有出现不同症状的日志不正常，包含：
> 	a. 几分钟内没有 Import 日志，过一段时间之后突然 Import 一大堆块
> 	b. 错误 Error importing block 0x0041b8f4d86ead019a4093363f790cee54522a813522a07a587fdfdb6b422e5c: Err(Other(ClientImport("Invalid operation in the pending changes tree: Tried to import or finalize node that is an ancestor of a previously finalized node")))
> 	c. 错误 Error importing block 0xfdcc28bfba7841156cff7f8f5f745fea0178d5ef26f4c825a5e731da5dca4d06: Err(UnknownParent)

> Encountered an error: WebSocket at Capacity: Exceeded max fragments.
> Enable a logger to see more information.

**Comment by HackFisher** [comment]
helper logger commands:

`-lws=trace,ws::handler=info`

**Comment by wi1dcard** [comment]
I'll update the nodes to the latest version v0.7.2 once I'm free. If the error `Encountered an error: WebSocket at Capacity: Exceeded max fragments.` consists, I'm going to try the option `-lws=trace,ws::handler=info` see if we can get more info from the detailed logs.

**Comment by wi1dcard** [comment]
Pasted logs from Dingtalk:

[websocket.log](https://github.com/darwinia-network/darwinia/files/5383718/websocket.log)
[p2p-g1.log](https://github.com/darwinia-network/darwinia/files/5383719/p2p-g1.log)
[p2p-g2.log](https://github.com/darwinia-network/darwinia/files/5383720/p2p-g2.log)
[websocket-exceeded-max-fragments.log](https://github.com/darwinia-network/darwinia/files/5383714/websocket-exceeded-max-fragments.log)
[subscan-crab-node.log](https://github.com/darwinia-network/darwinia/files/5383717/subscan-crab-node.log)

**Comment by AurevoirXavier** [comment]
Looks good with v0.9.3
