### ISSUE TITLE
EVM Integration Check List

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#619]
- [x] Header Digest
- [x] #624 
- [x] https://github.com/darwinia-network/darwinia-common/issues/512
- [x] https://github.com/darwinia-network/darwinia-common/issues/516
- [x] https://github.com/paritytech/frontier/issues/340

**Comment by HackFisher** [comment]
@AurevoirXavier What's the "Header Digest" meaning here?

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier What's the "Header Digest" meaning here?

DVM's special header digest items
