### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'returns Ok when no authority set change should be enacted;

### ISSUE THREAD

**Issue by feilun-feilun** [darwinia-network/darwinia#630]
Version: 0.8.9-fd8a732-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/panicking.rs:581:17
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC>::import_justification
   6: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
   7: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
   8: sp_consensus::import_queue::import_single_block_metered
   9: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  10: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  11: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
  12: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  13: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  14: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: std::thread::local::LocalKey<T>::with
  17: futures_executor::local_pool::block_on
  18: tokio::runtime::task::core::Core<T,S>::poll
  19: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  20: tokio::runtime::task::raw::poll
  21: tokio::runtime::blocking::pool::Inner::run
  22: tokio::runtime::context::enter
  23: std::sys_common::backtrace::__rust_begin_short_backtrace
  24: core::ops::function::FnOnce::call_once{{vtable.shim}}
  25: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/alloc/src/boxed.rs:1042:9
<alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/alloc/src/boxed.rs:1042:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/sys/unix/thread.rs:87:17
  26: start_thread
  27: clone

Thread 'tokio-runtime-worker' panicked at 'returns Ok when no authority set change should be enacted; qed;', /cargo/git/checkouts/substrate-a7fa553ead635512/7314a78/client/finality-grandpa/src/import.rs:682

**Comment by AurevoirXavier** [comment]
We don't maintain 0.8.9 anymore.

Try 0.9.5.

Re-open if still happen.
