### ISSUE TITLE
[Question / Bug]  Unfindable newly created address / account on subscan

### ISSUE THREAD

**Issue by Gregordy** [darwinia-network/darwinia#637]
I created an account but the [address](2oVrtRZAihPsEaM7mzRxyoTgpGTpBWgjhtJMTY5Xy8STr5zq) that was given to me afterwards is not findable on [subscan](https://darwinia.subscan.io/account/2oVrtRZAihPsEaM7mzRxyoTgpGTpBWgjhtJMTY5Xy8STr5zq).

Is there anything I missed (an indexing process ranning every X hour/day?) or is it an ongoing issue that is being worked out atm?

Thank you 😊

**Comment by AurevoirXavier** [comment]
At least own 0.1 RING. Otherwise your account won't be really created on the chain.
