### ISSUE TITLE
Does sudo from ordinary account(no multisig) require tx fee?

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#647]
https://crab.subscan.io/extrinsic/0xede0e9631686f23758e4fd997fb41770f2a3eddf2f9bd9e9265bcfdd3aed2e1a?event=4115114-1

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fcrab-rpc.darwinia.network#/explorer/query/4115114

**Comment by AurevoirXavier** [comment]
https://sourcegraph.com/github.com/paritytech/substrate/-/blob/frame/sudo/src/lib.rs#L162-163
