### ISSUE TITLE
Missed Justifications

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#679]
Hello, Crab Network validators!

Recently, we noticed that multiple nodes have NOT been sending GRANDPA justifications.

We found **22** justifications have been missed. The total number of validators was **73**.

Only about **70%** (`1 - 22/73 = 70%`) validators work well, which really causes **DANGEROUS** states for Crab Networks' finalization.

Therefore, we request the maintainers of these validators to check your node(s) following the guide #663.

---

**How to know if your node(s) does NOT work as expected?**

Click the link below and check the **Grandpa Vote** on that page. If the value is **ZERO**, you will need to check your node(s).
> https://crab.subscan.io/validator

---

Have a blessed day,

Darwinia Team

**Comment by AurevoirXavier** [comment]
Snapshots at Monday, July 12, 2021, week 28.

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/16152305/125272895-ee466380-e33e-11eb-9d92-32af46197227.png">

**Comment by AurevoirXavier** [comment]
Snapshot at UTC Wednesday, July 14, 2021, week 28.

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/16152305/125548779-92c9d719-81af-4e0e-956d-b758418c5128.png">

**Comment by ebygembleh** [comment]
good project

**Comment by AurevoirXavier** [comment]
Snapshot at UTC Monday, July 19, 2021, week 29.

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/16152305/126088656-66d3f93f-2a29-4af2-9661-918ff8b33678.png">
