### ISSUE TITLE
Different offchain-indexing behavior between darwinia-common and latest substrate

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#681]
darwinia-common

https://github.com/darwinia-network/darwinia-common/blob/2619efc54fd0ceba0174cc8bd3cce2ca7a6e8dde/client/cli/src/lib.rs#L482

substrate:

https://github.com/paritytech/substrate/blob/61a1d9c0587037d2df46c94d4feb7e971efaf790/client/cli/src/params/offchain_worker_params.rs#L72

**Comment by HackFisher** [comment]
https://github.com/paritytech/substrate/pull/8659

**Comment by AurevoirXavier** [comment]
#662 contains paritytech/substrate#8659
