### ISSUE TITLE
CI Checks Storage Prefix

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#692]
In #662, we change the `DarwiniaEthereumBacking` to `EthereumBacking` accidentally without migration.

**Comment by wi1dcard** [comment]
How we can checks it (using a script or analyzing the source code)?

**Comment by AurevoirXavier** [comment]
> How we can checks it (using a script or analyzing the source code)?

Run the node fetch the metadata through RPC, then compare with the production nodes'.

**Comment by wi1dcard** [comment]
Consider let @fewensa do this. What do you think, @fewensa ?

**Comment by AurevoirXavier** [comment]
> Consider let @fewensa do this. What do you think, @fewensa ?

I'll finish the checking script part. CI part might need your guys help.

**Comment by fewensa** [comment]
ok, I'll add a new workflow to run node.

**Comment by AurevoirXavier** [comment]
<img width="910" alt="image" src="https://user-images.githubusercontent.com/16152305/127779954-ea762b96-d7e6-4c9e-8c12-2d2c3d809330.png">

https://github.com/darwinia-network/darwinia-kit/blob/main/ci-bot/Cargo.toml

**Comment by AurevoirXavier** [comment]
https://github.com/darwinia-network/darwinia-common/pull/733
