### ISSUE TITLE
Remember to Initialize Relayer for S2S

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#703]
```rust
use frame_support::traits::Currency;
let _ = Ring::deposit_creating(&BridgeMillauMessages::relayer_fund_account_id(), 1 << 50);
```

Maybe the design will be changed.

But currently, if we don't initialize the relayer which will cause runtime panic.

https://github.com/paritytech/parity-bridges-common/blob/f16bb098cc/modules/messages/src/instant_payments.rs#L60

**Comment by HackFisher** [comment]
Related: https://github.com/paritytech/parity-bridges-common/pull/1111
