### ISSUE TITLE
error[E0465]: multiple rlib candidates for `darwinia_cli` found

### ISSUE THREAD

**Issue by browncrane** [darwinia-network/darwinia#707]
```
Doc-tests darwinia-cli
error[E0465]: multiple rlib candidates for `darwinia_cli` found
  --> /.../Projects/darwinia/cli/src/command.rs:28:5
   |
28 | use darwinia_cli::{Configuration, DarwiniaCli};
   |     ^^^^^^^^^^^^
   |
note: candidate #1: /.../Projects/darwinia/target/debug/deps/libdarwinia_cli-9ce5866332093a9c.rlib
  --> /.../Projects/darwinia/cli/src/command.rs:28:5
   |
28 | use darwinia_cli::{Configuration, DarwiniaCli};
   |     ^^^^^^^^^^^^
note: candidate #2: /.../Projects/darwinia/target/debug/deps/libdarwinia_cli.rlib
  --> /.../Projects/darwinia/cli/src/command.rs:28:5
   |
28 | use darwinia_cli::{Configuration, DarwiniaCli};
   |     ^^^^^^^^^^^^

error: aborting due to previous error

error: test failed, to rerun pass '--doc'
```

running on M1 mac,

Following read me,failing on `cargo test --all`

**Comment by AurevoirXavier** [comment]
Please don't modify the lock file.

`git reset --hard`.

Don't run `cargo update`, if you don't know what it does.

**Comment by browncrane** [comment]
`cargo update` has not been run.

before `git reset --hard`

```
darwinia git:(master) git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

After `git reset --hard`,  `cargo test --all` complain same error message.

**Comment by AurevoirXavier** [comment]
I see. And this is a “bug” of cargo. There is a crate named darwinia-cli and a mod named darwinia-cli too. But they are in different crates of this project. cargo build is okay. cargo test will put them into the same context. Try my branch xavier-drop-darwinia-cli which will fix this.

**Comment by browncrane** [comment]
cool, no error message on this branch.

**Comment by AurevoirXavier** [comment]
> cool, no error message on this branch.

#706 is merged. You can work on master now.
