### ISSUE TITLE
Slash Review: is punishment too heavy

### ISSUE THREAD

**Issue by hammeWang** [darwinia-network/darwinia#75]
### Description
if a validator's `unstake_threshold` is `n`, the global `offline_grace` is `g`, so when a validator has been offline for `n+g` times, it will be slashed `2**(n+g)* base_ratio`, up to `100%`.

considered the `base_ratio` is now `1/1000`, it is easy to be slashed 100%.

### Solution:
1. lower the `base_ratio`
2. optimize the slashing algorithm

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/darwinia/commit/12d92d0563e74afeabe0611a937965611e8d4f87#commitcomment-36138167

**Comment by AurevoirXavier** [comment]
> [12d92d0#commitcomment-36138167](https://github.com/darwinia-network/darwinia/commit/12d92d0563e74afeabe0611a937965611e8d4f87#commitcomment-36138167)

This's a bug. `slash_ratio` always be 100% not 'easy to be'.
