### ISSUE TITLE
Improve Release CI

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#766]
- [ ] Change srtool use Subwasm or Srtool actions
- [ ] https://github.com/darwinia-network/darwinia/issues/771
- [ ] Split build rust docs to other actions
- [ ] https://github.com/darwinia-network/darwinia/issues/775
- [x] https://github.com/darwinia-network/darwinia/issues/708

**Comment by HackFisher** [comment]
Related: https://github.com/darwinia-network/darwinia/pull/764#issuecomment-955851596

**Comment by fewensa** [comment]
- [ ] Change srtool use Subwasm or Srtool action
- [ ] https://github.com/darwinia-network/darwinia/issues/771
- [ ] Split rust docs to other actions
