### ISSUE TITLE
希望浏览器或者钱包可以有个统计节点出块的功能

### ISSUE THREAD

**Issue by doudouyaoniubi** [darwinia-network/darwinia#77]
希望浏览器或者钱包可以有个统计节点出块的功能，现在看着不是很方便。

提交节点： Bit Cat

**Comment by purplieee** [comment]
我用的优盾钱包有一键归集的功能，冷热钱包结合也安全方便，使用感还不错

**Comment by HackFisher** [comment]
Issue moved to [darwinia-network/web-wallet #1](https://github.com/darwinia-network/web-wallet/issues/1) via [**ZenHub**](https://www.zenhub.com/)
