### ISSUE TITLE
Limit to `u32::MAX` Gas?

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#785]
> https://github.com/darwinia-network/darwinia/blob/master/runtime/crab/src/pallets/evm_.rs#L65

**Comment by AsceticBear** [comment]
Waiting for https://github.com/darwinia-network/darwinia-common/pull/1173

**Comment by HackFisher** [comment]
Not fixed? https://github.com/darwinia-network/darwinia/blob/b5e79a93359855f20f6f9f1bcf89e8749f9316d1/runtime/crab/src/pallets/evm.rs#L142

**Comment by AsceticBear** [comment]
Waiting for next upgrade
