### ISSUE TITLE
Remove claim pallet in Crab's next runtime

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#870]
And the ui will be removed after that, all the unclaimed CRAB tokens will be claimed using new solution, aka. using airdrop tools.

And, the token balances of unclaimed token will need to be migrated to a multisig address for airdrop tool to use.

**Comment by 1022ranji** [comment]
- [ ] Runtime 升级前：发公告告知社区将在下次crab升级时移除claim模块，将直接发送CRAB至未领取的地址，用户可在crab smart chain 上查看。附加之前空投的规则。 @1022ranji @ZolaxZola 
- [ ] Runtime 升级后：Wormhole UI 移除 Airdrop @sxlwar @JayJay1024 
- [ ] Runtime 升级后：导出未领取的地址，使用进化星球的空投工具发送CRAB至导出的地址 @JayJay1024 @ZolaxZola 
- [ ] CRAB发送完成后，发公告告知社区已完成全部空投等。 @1022ranji @ZolaxZola

**Comment by AurevoirXavier** [comment]
> Runtime 升级前：发公告告知社区将在下次crab升级时移除claim模块，将直接发送CRAB至未领取的地址，用户可在crab smart chain 上查看。附加之前空投的规则。

I don't think we should release all the un-claims.

**Comment by HackFisher** [comment]
Replaced by #873 and https://crab.subscan.io/democracy_proposal/18
