### ISSUE TITLE
Clean Unused Deps

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#896]
Use `frame_support::log` instead `log` if we have `frame_support` already.

**Comment by ECJ222** [comment]
Hi @AurevoirXavier,

Can I take on this issue?

**Comment by AurevoirXavier** [comment]
> Hey @AurevoirXavier,
> 
> If I understand your issue correctly, you are saying the `frame_support` pallet should be replaced with `log` instead wherever it is referenced.

That's a part of this issue.

---
 
Also checks [cargo-udeps](https://github.com/est31/cargo-udeps).

**Comment by ECJ222** [comment]
After performing checks, There was a small issue with the syn crate not being updated to the current version.

The `sp-core-hashing-proc-macro` dependency on darwinia is referencing an older version of the `syn` crate which requires the `parse_quote_spanned` macro which at 1.0.81 has not yet been created.

**Comment by AurevoirXavier** [comment]
> After performing checks, There was a small issue with the syn crate not being updated to the current version.
> 
> The `sp-core-hashing-proc-macro` dependency on darwinia is referencing an older version of the `syn` crate which requires the `parse_quote_spanned` macro which at 1.0.81 has not yet been created.

```
cargo update -p syn --precise 1.0.96
```

**Comment by ECJ222** [comment]
running `udeps` doesn't work, it's conflicting with the build scripts `metadata`.

There's an issue already open for error:  [#97](https://github.com/est31/cargo-udeps/issues/97) [#256](https://github.com/LibertyDSNP/frequency/issues/256#issuecomment-1228666030)

**Comment by ECJ222** [comment]
I found an alternative that works [cargo-machete](https://crates.io/crates/cargo-machete), What do you think?

**Comment by AurevoirXavier** [comment]
Could you open a PR? I'll check the detail.

**Comment by ECJ222** [comment]
Yeah sure @AurevoirXavier, I just did.
