### ISSUE TITLE
Security review: PalletId::into_account

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#903]
https://github.com/darwinia-network/darwinia/blob/8cf178d528a77af4995ccb8c4001e39c58184ae8/runtime/crab/src/migrations.rs#L47

**Comment by AurevoirXavier** [comment]
Only one usage found, and it's safe.
<img width="438" alt="image" src="https://user-images.githubusercontent.com/16152305/177342416-3e18a400-4754-46fa-99d3-a048b380750b.png">

Further reading: [The Undercurrent of `AccountIdConversion`](https://app.skiff.com/docs/912915e7-ee50-448d-947e-f4639f12b8d0#+sOKxqfoeAtnzc08J5xS7Kv4GTFOX+kqKT6Po/2NN+s=)
