### ISSUE TITLE
Do not use default MessageDispatch from SDK, customize it in runtime.

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#905]
It is recommended not to use FromBridgedChainMessageDispatch of runtime-common, instead, each runtime implements it by itself.

- This default implementation passes a lot of generics and is less readable.
- According to [#103](https://github.com/darwinia-network/darwinia-messages-substrate/issues/103), the default implementation of Darwinia is not used here, but it is easy to misunderstand that the settlement fee is done on the target chain.
- Each runtime implements its own primitives that are more convenient to obtain external runtimes, e.g. derive_ethereum_account for Ethereum origin.

**Comment by AsceticBear** [comment]
This issue looks like in `darwinia-common` repo scope, should we move it there? @AurevoirXavier

**Comment by AsceticBear** [comment]
I think this is solved. Close it.
