### ISSUE TITLE
Crab Kusama Chain Spec with bootnodes

### ISSUE THREAD

**Issue by sourabhniyogi** [darwinia-network/darwinia#927]
Can you post the crab [kusama paraID 2105] chainspec -- including bootnodes? We [Polkaholic.io] are building a multi-chain block explorer with XCM support cf
https://crab.polkaholic.io/chain/crab
and are attempting to run a full archive node (to index Crab blocks including traces, xcm transfers into and out of Crab, etc.) and couldn't find this in your repo.

Thank you!

**Comment by AurevoirXavier** [comment]
https://github.com/darwinia-network/darwinia-parachain/tree/main/res
