### ISSUE TITLE
Review Inflation using  IntegerSquareRoot Linear to replace PiecewiseLinear

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#95]
https://github.com/darwinia-network/darwinia/blob/develop/srml/staking/src/inflation.rs

**Comment by AurevoirXavier** [comment]
@HackFisher, can be closed?

**Comment by HackFisher** [comment]
Duplicate:
https://github.com/darwinia-network/darwinia/issues/181
