### ISSUE TITLE
Optimize BLS precompile

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia#972]
https://github.com/paritytech/substrate/pull/13031

**Comment by AurevoirXavier** [comment]
Was moved to https://github.com/paritytech/ark-substrate.

**Comment by hackfisher** [comment]
https://eips.ethereum.org/EIPS/eip-7600

EIP-2537: Precompile for BLS12-381 curve operations

Included in Prague/Electra network upgrade

**Comment by hackfisher** [comment]
https://github.com/darwinia-network/darwinia/issues/1501
