### ISSUE TITLE
Develop branch client get panic

### ISSUE THREAD

**Issue by freehere107** [darwinia-network/darwinia#98]
0|darwinia-alice  | 2019-11-21 01:36 +00:00: 2019-11-21 01:36:12 Pre-sealed block for proposal at 253968. Hash now 0x9a706423dc49df5316c183758389fbed1871e74223d44a01d626e3eba15fc5b0, previously 0xdad40453a38eab2c365844cd6893fb6be23b962c38e6bb06b9b1a1ca8c4b63eb.
0|darwinia-alice  | 2019-11-21 01:36 +00:00:
0|darwinia-alice  | 2019-11-21 01:36 +00:00: ====================
0|darwinia-alice  | 2019-11-21 01:36 +00:00:
0|darwinia-alice  | 2019-11-21 01:36 +00:00: Version:
0|darwinia-alice  | 2019-11-21 01:36 +00:00: 0.3.2-0c88d53-x86_64-linux-gnu
0|darwinia-alice  | 2019-11-21 01:36 +00:00:
0|darwinia-alice  | 2019-11-21 01:36 +00:00:
0|darwinia-alice  | 2019-11-21 01:36 +00:00: stack backtrace:
0|darwinia-alice  | 2019-11-21 01:36 +00:00:
0|darwinia-alice  | 2019-11-21 01:36 +00:00:
0|darwinia-alice  | 2019-11-21 01:36 +00:00:
0|darwinia-alice  | 2019-11-21 01:36 +00:00: 0
0|darwinia-alice  | 2019-11-21 01:36 +00:00: :
0|darwinia-alice  | 2019-11-21 01:36 +00:00: substrate_panic_handler::set::{{closure}}
0|darwinia-alice  | 2019-11-21 01:36 +00:00:    1: std::panicking::rust_panic_with_hook
0|darwinia-alice  | 2019-11-21 01:36 +00:00:              at src/libstd/panicking.rs:477
0|darwinia-alice  | 2019-11-21 01:36 +00:00:    2: std::panicking::continue_panic_fmt
0|darwinia-alice  | 2019-11-21 01:36 +00:00:              at src/libstd/panicking.rs:380
0|darwinia-alice  | 2019-11-21 01:36 +00:00:    3: std::panicking::begin_panic_fmt
0|darwinia-alice  | 2019-11-21 01:36 +00:00:              at src/libstd/panicking.rs:335
0|darwinia-alice  | 2019-11-21 01:36 +00:00:    4: node_runtime::api::dispatch
0|darwinia-alice  | 2019-11-21 01:36 +00:00:    5: std::panicking::try::do_call
0|darwinia-alice  | 2019-11-21 01:36 +00:00:    6: __rust_maybe_catch_panic
0|darwinia-alice  | 2019-11-21 01:36 +00:00:              at src/libpanic_unwind/lib.rs:80
0|darwinia-alice  | 2019-11-21 01:36 +00:00:    7: substrate_executor::native_executor::safe_call
0|darwinia-alice  | 2019-11-21 01:36 +00:00:    8: std::thread::local::LocalKey<T>::with
0|darwinia-alice  | 2019-11-21 01:36 +00:00:    9: <node_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   10: std::thread::local::LocalKey<T>::with
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   11: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_aux
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   12: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_call_with_native_else_wasm_strategy
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   13: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_using_consensus_failure_handler
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   14: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state
0|darwinia-alice  | 2019-11-21 01:36 +00:00: Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   16: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   17: <substrate_consensus_babe::BabeBlockImport<B,E,Block,I,RA,PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   18: core::task::poll::Poll<T>::map
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   19: <futures_util::try_future::map_ok::MapOk<Fut,F> as core::future::future::Future>::poll
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   20: futures_util::try_future::try_chain::TryChain<Fut1,Fut2,Data>::poll
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   21: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   22: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   23: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   24: <futures::future::select::Select<A,B> as futures::future::Future>::poll
0|darwinia-alice  | 2019-11-21 01:36 +00:00:
0|darwinia-alice  | 2019-11-21 01:36 +00:00:  25: futures::future::chain::Chain<A,B,C>::poll
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   26: futures::task_impl::std::set
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   27: std::panicking::try::do_call
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   28: __rust_maybe_catch_panic
0|darwinia-alice  | 2019-11-21 01:36 +00:00:              at src/libpanic_unwind/lib.rs:80
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   29: tokio_threadpool::task::Task::run
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   30: tokio_threadpool::worker::Worker::run_task
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   31: tokio_threadpool::worker::Worker::run
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   32: std::thread::local::LocalKey<T>::with
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   33: std::thread::local::LocalKey<T>::with
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   34: std::thread::local::LocalKey<T>::with
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   35: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   36: std::thread::local::LocalKey<T>::with
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   37: std::thread::local::LocalKey<T>::with
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   38: std::sys_common::backtrace::__rust_begin_short_backtrace
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   39: std::panicking::try::do_call
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   40: __rust_maybe_catch_panic
0|darwinia-alice  | 2019-11-21 01:36 +00:00:              at src/libpanic_unwind/lib.rs:80
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   41: core::ops::function::FnOnce::call_once{{vtable.shim}}
0|darwinia-alice  | 2019-11-21 01:36 +00:00: A>>::call_once
0|darwinia-alice  | 2019-11-21 01:36 +00:00:              at /rustc/6ef275e6c3cb1384ec78128eceeb4963ff788dca/src/liballoc/boxed.rs:922
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   43: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
0|darwinia-alice  | 2019-11-21 01:36 +00:00:              at /rustc/6ef275e6c3cb1384ec78128eceeb4963ff788dca/src/liballoc/boxed.rs:922
0|darwinia-alice  | 2019-11-21 01:36 +00:00:       std::sys_common::thread::start_thread
0|darwinia-alice  | 2019-11-21 01:36 +00:00:              at src/libstd/sys_common/thread.rs:13
0|darwinia-alice  | 2019-11-21 01:36 +00:00:       std::sys::unix::thread::Thread::new::thread_start
0|darwinia-alice  | 2019-11-21 01:36 +00:00:              at src/libstd/sys/unix/thread.rs:79
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   44: start_thread
0|darwinia-alice  | 2019-11-21 01:36 +00:00:   45: __clone
0|darwinia-alice  | 2019-11-21 01:36 +00:00:
0|darwinia-alice  | 2019-11-21 01:36 +00:00:
0|darwinia-alice  | 2019-11-21 01:36 +00:00: Thread 'main-tokio-1' panicked at 'Bad input data provided to execute_block: Error decoding field Block.extrinsics', node/runtime/src/lib.rs:484

**Comment by HackFisher** [comment]
@freehere107 what's the commit of this version?

**Comment by freehere107** [comment]
Maybe 2cff68f970c953f0200a37b51013daa07b567c97. Not recent commit

**Comment by HackFisher** [comment]
How about try with latest version?

**Comment by AurevoirXavier** [comment]
```rust
2019-11-21 12:03:29 Running in --dev mode, RPC CORS has been disabled.
2019-11-21 12:03:29 Darwinia Crayfish Node
2019-11-21 12:03:29   version 0.3.2-8a148c6-x86_64-macos
2019-11-21 12:03:29   _____                      _       _       
2019-11-21 12:03:29  |  __ \                   (_)     (_)      
2019-11-21 12:03:29  | |  | | __ _ _ ____      ___ _ __  _  __ _ 
2019-11-21 12:03:29  | |  | |/ _` | '__\ \ /\ / / | '_ \| |/ _` |
2019-11-21 12:03:29  | |__| | (_| | |   \ V  V /| | | | | | (_| |
2019-11-21 12:03:29  |_____/ \__,_|_|    \_/\_/ |_|_| |_|_|\__,_|
2019-11-21 12:03:29 Chain specification: Development
2019-11-21 12:03:29 Node name: horrible-donkey-4128
2019-11-21 12:03:29 Roles: "AUTHORITY"

====================

Version: 0.3.2-8a148c6-x86_64-macos

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: substrate_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::thread::local::LocalKey<T>::with
   6: substrate_state_machine::basic::BasicExternalities::execute_with_storage
   7: <node_runtime::GenesisConfig as sr_primitives::BuildStorage>::assimilate_storage
   8: sr_primitives::BuildStorage::build_storage
   9: <&substrate_chain_spec::chain_spec::ChainSpec<G,E> as sr_primitives::BuildStorage>::build_storage
  10: substrate_client::client::Client<B,E,Block,RA>::new
  11: substrate_client_db::new_client
  12: substrate_service::builder::ServiceBuilder<(),(),TCfg,TGen,TCSExt,(),(),(),(),(),(),(),(),(),()>::new_full
  13: node_cli::service::new_full
  14: substrate_cli::ParseAndPrepareRun<RP>::run
  15: node_cli::run
  16: darwinia::main
  17: std::rt::lang_start::{{closure}}
  18: std::panicking::try::do_call
  19: __rust_maybe_catch_panic
  20: std::rt::lang_start_internal
  21: main


Thread 'main' panicked at 'Number of keys in session handler and session keys does not match', /Users/xavier/.cargo/git/checkouts/substrate-a7fa553ead635512/d2c4b0d/srml/session/src/lib.rs:407

This is a bug. Please report it at:

   https://github.com/darwinia-network/darwinia/issues/new
```

Seems need to update the `chain_spec`

**Comment by AurevoirXavier** [comment]
[session handlers](https://github.com/darwinia-network/darwinia/blob/0c88d533deb3674eb9fc6c34257b4f5f3b59267e/node/runtime/src/lib.rs#L248)
[session keys](https://github.com/darwinia-network/darwinia/blob/0c88d533deb3674eb9fc6c34257b4f5f3b59267e/node/cli/src/chain_spec.rs#L64)
